#!/usr/bin/env bash
# B002 - Add ALE OnLogin hook to playerbots bot login
# Issue 324: playerbots don't trigger PLAYER_EVENT_ON_LOGIN
# Parallelizable: Yes (unique files)

# {{{ patch_B002_playerbots_ale_login_hook
patch_B002_playerbots_ale_login_hook() {
    local FILE="${AC_CODE_DIR}/modules/mod-playerbots/src/Bot/RandomPlayerbotMgr.cpp"
    local CMAKE_FILE="${AC_CODE_DIR}/modules/mod-playerbots/mod-playerbots.cmake"
    [[ ! -f "${FILE}" ]] && return 0

    # Check if patch already applied (look for our hook call)
    if grep -q "sALE->OnLogin(bot)" "${FILE}"; then
        return 0  # Already patched
    fi

    echo "  [B002] mod-playerbots: ALE login hook"

    # Step 1: Create mod-playerbots.cmake to add ALE include directories and MOD_ALE define
    if [[ ! -f "${CMAKE_FILE}" ]] || ! grep -q "MOD_ALE_PATH" "${CMAKE_FILE}"; then
        cat > "${CMAKE_FILE}" << 'EOF'
# mod-playerbots.cmake
# Generated by patch B002 (Issue 324)
# Adds mod-ale include directories so playerbots can call ALE hooks

message(STATUS "  +- mod-playerbots.cmake: MOD_ALE_FOUND=${MOD_ALE_FOUND} MOD_ALE_PATH=${MOD_ALE_PATH}")
if (MOD_ALE_FOUND)
    message(STATUS "  +- mod-playerbots: Adding mod-ale include paths: ${MOD_ALE_PATH}/LuaEngine")
    target_include_directories(modules
        PUBLIC
            ${MOD_ALE_PATH}/LuaEngine)
    target_compile_definitions(modules PUBLIC MOD_ALE)
endif()
EOF
    fi

    # Step 2: Add include for LuaEngine.h
    if ! grep -q '#include "LuaEngine.h"' "${FILE}"; then
        sed -i '/#include "GridNotifiersImpl.h"/a \
\
// ALE Lua engine for login hooks (Issue 324)\
#ifdef MOD_ALE\
#include "LuaEngine.h"\
#endif' "${FILE}"
    fi

    # Step 3: Add sALE->OnLogin(bot) call at END of OnBotLoginInternal
    sed -i '/bot->RemovePlayerFlag(PLAYER_FLAGS_NO_XP_GAIN);/{
        n
        a\
\
    // Trigger ALE Lua login hook so Lua scripts can initialize bot behaviors\
    // This ensures bots are treated identically to real players (Issue 324)\
    // Placed at END of function so bot is fully initialized (Issue 332)\
#ifdef MOD_ALE\
    sALE->OnLogin(bot);\
#endif
    }' "${FILE}"
}
# }}}

# {{{ unpatch_B002_playerbots_ale_login_hook
unpatch_B002_playerbots_ale_login_hook() {
    local FILE="${AC_CODE_DIR}/modules/mod-playerbots/src/Bot/RandomPlayerbotMgr.cpp"
    [[ ! -f "${FILE}" ]] && return 0

    # Remove ALE include block
    if grep -q '#include "LuaEngine.h"' "${FILE}"; then
        sed -i '/\/\/ ALE Lua engine for login hooks/,/#endif.*\/\/ MOD_ALE include/d' "${FILE}"
        sed -i '/\/\/ ALE Lua engine for login hooks (Issue 324)/,/^#endif$/{ /^#endif$/d; d; }' "${FILE}"
    fi

    # Remove OnLogin hook call
    if grep -q "sALE->OnLogin(bot)" "${FILE}"; then
        sed -i '/\/\/ Trigger ALE Lua login hook/,/^#endif.*sALE/d' "${FILE}"
        sed -i '/Trigger ALE Lua login hook/,/sALE->OnLogin(bot)/{ N; N; N; N; d; }' "${FILE}" 2>/dev/null || true
    fi
}
# }}}
