--------------------------------------------------------------------------------
-- death-knight-souls.lua (issue 718, layer 1: the sacrifice)
--
-- On basic a death knight is what one of the player's heroes became. Ritz,
-- 2026-09-23: "When you create a DK it deletes that level 55 character that
-- you leveled to that level." And 2026-09-25: "Can we have a static
-- Sargobras who offers to help them leave Acherus in exchange for a powerful
-- soul? One hero for the Lich King, one death knight for the living..."
--
--   1. The ledger: a new death knight's first login writes an "owed" row
--      (characters database, basic_718_souls, E041). A death knight made
--      before this rule has no row and is never held.
--   2. The gate: an owing death knight who steps out of the necropolis
--      (map 609, area 4342) is sent back to Sargobras before the Lich King,
--      who withholds the first quest until the soul is paid (spawns in
--      25-death-knight-sargobras, E040; a second one stays in the Ebon Hold
--      on map 0, for the undo after the chain).
--   3. The trade: Sargobras lists the account's characters at level 55 or
--      higher ("level 55 or greater"), death knights left out. The chosen
--      one moves to a hidden holding account ("put into a holding area
--      in-case they change their mind"), one per player account, since an
--      account holds at most 10 characters per realm. The death knight
--      learns its professions ("inherit the professions of the character
--      it sacrificed") and may leave.
--   4. The undo: "Sargobras in Acherus can reverse this at any time,
--      deleting the death knight and returning the player character to
--      their account. They will be exactly the same except they will have
--      the DK haunted eyes and skin color and such because they are
--      canonically undead now. Sucks to be them..."
--
-- Moving characters between accounts and erasing one are done with the
-- server's own console commands (.character changeaccount, .character
-- erase), which keep its cache of who owns what correct; a bare UPDATE
-- would leave that cache stale until a restart.
--------------------------------------------------------------------------------

-- {{{ local function script_dir
-- The directory this file sits in, so the data file is found wherever the
-- lua_scripts tree is linked from (as in outland-flights.lua).
local function script_dir()
    local src = debug.getinfo(1, "S").source
    return (src:sub(1, 1) == "@" and src:sub(2) or src):match("^(.*[/\\])") or "./"
end
-- }}}

-- generated by scripts/generate-basic-death-knight-soul-data from the client's files
local DATA = dofile(script_dir() .. "data/death-knight-soul-data.lua")

local GOSSIP_EVENT_ON_HELLO  = 1
local GOSSIP_EVENT_ON_SELECT = 2
local PLAYER_EVENT_ON_LOGIN       = 3
local PLAYER_EVENT_ON_UPDATE_ZONE = 27
local PLAYER_EVENT_ON_FIRST_LOGIN = 30
local PLAYER_EVENT_ON_UPDATE_AREA = 47              -- mod-ale Hooks.h: (event, player, oldArea, newArea)
local PLAYER_EVENT_ON_LEARN_SPELL = 44              -- mod-ale Hooks.h: (event, player, spellId)
local GOSSIP_ICON_CHAT = 0

local CLASS_DEATH_KNIGHT = 6
local SARGOBRAS          = 7180001                  -- creature, from 25-death-knight-sargobras
local TEXT_OWED, TEXT_GIVEN, TEXT_OTHER = 7180001, 7180002, 7180003
local SOUL_MIN_LEVEL     = 55

-- where an owing death knight may be, and where it is sent back to
local ACHERUS_MAP        = 609                      -- the Scarlet Enclave, where the intro chain is played
local ACHERUS_AREA       = 4342                     -- "Acherus: The Ebon Hold" on map 609: the necropolis itself (AreaTable.dbc)
local SARGOBRAS_SPOT     = { map = 609, x = 2352.6, y = -5666.8, z = 426.07, o = 3.77 } -- a step in front of the Heart of Acherus one (spawn 7180002), facing him
local LICH_KING          = 25462                    -- gives the chain's first quest, In Service Of The Lich King (12593)
local INTRO_LAST_QUEST   = 13166                    -- The Battle For The Ebon Hold: the chain's last shared quest
local FLAME_SPELL        = 51195                    -- Cosmetic - Low Poly Fire (Spell.dbc): a soft flame, no harm
local VANISH_AFTER_MS    = 3000                     -- how long he burns before he is gone
local SARGOBRAS_ACHERUS_SPAWN = 7180002             -- the Heart of Acherus one (25-death-knight-sargobras); the Ebon Hold one stays seen, for the undo

local STATE_OWED, STATE_GIVEN, STATE_RETURNING = 0, 1, 2
local INTID_RETURN       = 1                        -- the undo; a soul's own intid is its guid (always far above 2)
local INTID_CLAN         = 2                        -- naming the clan later, if the trade's name failed (617l)
local HOLDING_PREFIX     = "SOULS"                  -- holding account name: SOULS<player account id>
local RETURN_DELAY_MS    = 5000                     -- after the erase, before the soul is moved back (the erase's writes land first)

-- {{{ local function ledger
-- The death knight's row, or nil when it has none (never held).
local function ledger(dk_guid)
    local q = CharDBQuery("SELECT soul, soul_account, holding_account, state FROM basic_718_souls WHERE dk = " .. dk_guid)
    if not q then return nil end
    return { soul = q:GetUInt32(0), soul_account = q:GetUInt32(1), holding = q:GetUInt32(2), state = q:GetUInt32(3) }
end
-- }}}

-- {{{ local function allowed_here
-- An owing death knight may only be inside the necropolis (map 609, area
-- 4342). Ritz, 2026-09-29: "acherus shouldn't be left at all until they
-- comply" -- not the Enclave below, and not the Ebon Hold on map 0.
local function allowed_here(player, area)
    return player:GetMapId() == ACHERUS_MAP and (area == ACHERUS_AREA or player:GetAreaId() == ACHERUS_AREA)
end
-- }}}

-- {{{ local function hold_selection
-- While a soul is owed, no creature but Sargobras can be selected by the
-- death knight (owner, 2026-09-29: the Lich King "should be untargetable
-- unless you've given a soul. In-fact, it'd be great if all the NPCs
-- were"). The per-player rule is issue 164: a source patch (B040) and its
-- Lua calls (B041). A server built before them has no such call; that is
-- logged as an error, not passed over: the death knight is then held only
-- by the gate and the Lich King's withheld quest.
local function hold_selection(player, hold)
    local ok, err = pcall(function()
        if hold then player:SetUnselectableCreatures({ SARGOBRAS }, true)
        else player:ClearUnselectableCreatures() end
    end)
    if not ok then
        print("[death-knight-souls] ERROR: could not " .. (hold and "hold" or "release") .. " what "
            .. player:GetName() .. " can select (is the server built with B040/B041, issue 164?): " .. tostring(err))
    end
end
-- }}}

-- {{{ local function intro_done
-- Whether the death knight has finished Acherus's quest chain: "The Battle
-- For The Ebon Hold" (13166) turned in, the last quest both factions share
-- (only the trips to Stormwind or Orgrimmar come after). Sargobras gives a
-- soul back only then (owner, 2026-09-29: "Sargobras can only return a DK
-- to life once they've completed the intro zone").
local function intro_done(player)
    return player:GetQuestRewardStatus(INTRO_LAST_QUEST)
end
-- }}}

-- {{{ local function vanish
-- His part done, Sargobras goes up in a soft flame and is gone (owner,
-- 2026-09-29: "Can we make him invisible over a short duration after
-- you've made your choice of who to sacrifice? Maybe a soft fire
-- effect."). The flame burns a few seconds (everyone near sees the flame),
-- then he is gone for the one who traded alone (per-player hiding, issue
-- 164: "okay let's build that mechanism then"); other death knights still
-- see him and trade with him. He stays hidden from them at later logins
-- (on_login). A server built without B040/B041 has no hiding call: logged
-- as an error, he simply stays.
local function hide_from(player)
    local ok, err = pcall(function() player:SetCreatureSpawnHidden(SARGOBRAS_ACHERUS_SPAWN, true) end)
    if not ok then
        print("[death-knight-souls] ERROR: could not hide Sargobras from " .. player:GetName()
            .. " (is the server built with B040/B041, issue 164?): " .. tostring(err))
    end
end
local function vanish(creature, player)
    creature:CastSpell(creature, FLAME_SPELL, true)
    local guid = player:GetGUID()
    creature:RegisterEvent(function()
        local p = GetPlayerByGUID(guid)
        if p then hide_from(p) end
    end, VANISH_AFTER_MS, 1)
end
-- }}}

-- {{{ local function check_gate
-- Owing (state 0) and outside: back to Sargobras. Given, returning, or no
-- row: free to go.
local function check_gate(player, area)
    if player:GetClass() ~= CLASS_DEATH_KNIGHT then return end
    local row = ledger(player:GetGUIDLow())
    if not row or row.state ~= STATE_OWED then return end
    if allowed_here(player, area) then return end
    local s = SARGOBRAS_SPOT
    -- Already standing at his feet: the area lookup disagrees with the map
    -- here, and teleporting again would only loop. Say so instead.
    if player:GetMapId() == s.map and player:GetDistance(s.x, s.y, s.z) < 10 then
        print(string.format("[718] ERROR: the spot before Sargobras reads as area %d, not %d; the gate cannot hold here", player:GetAreaId(), ACHERUS_AREA))
        return
    end
    player:Teleport(s.map, s.x, s.y, s.z, s.o)
    player:SendBroadcastMessage("Sargobras says: Not so fast. The living will want to know who you were. Come and tell me.")
end
-- }}}

-- {{{ local function holding_account
-- The player account's own holding account, made the first time it is
-- needed with a random password nobody keeps (so it can never be logged
-- into). Returns its id and name, or nil and a reason.
local function holding_account(account_id)
    local name = HOLDING_PREFIX .. account_id
    local q = AuthDBQuery("SELECT id FROM account WHERE username = '" .. name .. "'")
    if not q then
        local chars = "abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789"
        local pw = {}
        for i = 1, 16 do local k = math.random(#chars); pw[i] = chars:sub(k, k) end
        pw = table.concat(pw)
        RunCommand(".account create " .. name .. " " .. pw)
        q = AuthDBQuery("SELECT id FROM account WHERE username = '" .. name .. "'")
        if not q then return nil, "the holding account " .. name .. " could not be created" end
    end
    return q:GetUInt32(0), name
end
-- }}}

-- {{{ local function candidates
-- The account's characters at level 55 or higher, death knights left out.
local function candidates(player)
    local q = CharDBQuery("SELECT guid, name, level FROM characters WHERE account = " .. player:GetAccountId()
        .. " AND level >= " .. SOUL_MIN_LEVEL .. " AND class <> " .. CLASS_DEATH_KNIGHT
        .. " AND guid <> " .. player:GetGUIDLow() .. " AND deleteInfos_Account IS NULL ORDER BY level DESC, name")
    local out = {}
    if q then
        repeat
            out[#out + 1] = { guid = q:GetUInt32(0), name = q:GetString(1), level = q:GetUInt32(2) }
        until not q:NextRow()
    end
    return out
end
-- }}}

-- {{{ maxed professions at training
-- A death knight player's first two primary professions learned from a
-- trainer are raised to Artisan 300 at once (owner, 2026-09-30: "what about
-- DK players? They should have maxed professions too, but only for the
-- first ones they train"). Keyed by each profession's apprentice spell:
-- { skill line, its Artisan rank spell } (Spell.dbc; the Artisan rank
-- spell sets the skill's maximum to 300). Counted in basic_718_maxed, so
-- dropping one and training another doesn't max it again. Professions
-- carried from the soul (carry_professions) are not trained: skipped.
local APPRENTICE_TO_ARTISAN = {
    [2259]  = { 171, 11611 },  -- Alchemy
    [2018]  = { 164, 9785  },  -- Blacksmithing
    [7411]  = { 333, 13920 },  -- Enchanting
    [4036]  = { 202, 12656 },  -- Engineering
    [45357] = { 773, 45360 },  -- Inscription
    [25229] = { 755, 28895 },  -- Jewelcrafting
    [2108]  = { 165, 10662 },  -- Leatherworking
    [3908]  = { 197, 12180 },  -- Tailoring
    [2366]  = { 182, 11993 },  -- Herbalism
    [2575]  = { 186, 10248 },  -- Mining
    [8613]  = { 393, 10768 },  -- Skinning
}
local MAXED_AT_TRAINING = 2
local carrying = {}                                  -- death knight guid -> true while the soul's professions are copied

local function on_learn_spell(event, player, spell)
    local prof = APPRENTICE_TO_ARTISAN[spell]
    if not prof or player:GetClass() ~= CLASS_DEATH_KNIGHT then return end
    local guid = player:GetGUIDLow()
    if carrying[guid] then return end                -- the soul's, not trained
    local q = CharDBQuery("SELECT COUNT(*) FROM basic_718_maxed WHERE dk = " .. guid)
    if q and q:GetUInt32(0) >= MAXED_AT_TRAINING then return end
    player:LearnSpell(prof[2])                       -- Artisan: the maximum becomes 300
    player:SetSkill(prof[1], 4, 300, 300)            -- step 4 = Artisan
    CharDBExecute(string.format("INSERT IGNORE INTO basic_718_maxed (dk, skill) VALUES (%d, %d)", guid, prof[1]))
    player:SendBroadcastMessage("What you learned in life comes back to you at once.")
end
-- }}}

-- {{{ local function carry_professions
-- Teach the death knight the soul's professions: the recipes and rank
-- spells first (a rank spell opens the skill), then the skill values
-- exactly as the soul had them. Read before the soul moves accounts.
local function carry_professions(player, soul_guid)
    carrying[player:GetGUIDLow()] = true             -- what it learns here is the soul's, not trained
    local learned, skills = 0, 0
    local q = CharDBQuery("SELECT spell FROM character_spell WHERE guid = " .. soul_guid)
    if q then
        repeat
            local spell = q:GetUInt32(0)
            if DATA.profession_spells[spell] and not player:HasSpell(spell) then
                player:LearnSpell(spell)
                learned = learned + 1
            end
        until not q:NextRow()
    end
    q = CharDBQuery("SELECT skill, value, max FROM character_skills WHERE guid = " .. soul_guid)
    if q then
        repeat
            local skill, value, max = q:GetUInt32(0), q:GetUInt32(1), q:GetUInt32(2)
            if DATA.professions[skill] then
                -- step: the rank the maximum belongs to (75 Apprentice = 1 ... 450 Grand Master = 6)
                player:SetSkill(skill, math.max(1, math.ceil(max / 75)), value, max)
                skills = skills + 1
            end
        until not q:NextRow()
    end
    carrying[player:GetGUIDLow()] = nil
    return learned, skills
end
-- }}}

-- {{{ local function give_soul
local function give_soul(player, soul_guid)
    local account = player:GetAccountId()
    local soul
    for _, c in ipairs(candidates(player)) do if c.guid == soul_guid then soul = c end end
    if not soul then
        player:SendBroadcastMessage("Sargobras says: That one isn't yours to give, or isn't ready.")
        return
    end
    local holding_id, holding_name = holding_account(account)
    if not holding_id then
        print("[death-knight-souls] ERROR: " .. holding_name .. "; " .. player:GetName() .. " keeps its soul for now")
        player:SendBroadcastMessage("Sargobras says: Something's wrong on my end. Keep your soul a little longer. (The server log says why.)")
        return
    end
    local learned, skills = carry_professions(player, soul.guid)
    RunCommand(".character changeaccount " .. holding_name .. " " .. soul.name)
    local check = CharDBQuery("SELECT account FROM characters WHERE guid = " .. soul.guid)
    if not check or check:GetUInt32(0) ~= holding_id then
        print("[death-knight-souls] ERROR: moving " .. soul.name .. " to " .. holding_name .. " failed (is that account full?); "
            .. player:GetName() .. " keeps its soul for now")
        player:SendBroadcastMessage("Sargobras says: The soul slipped through my fingers. Try again later. (The server log says why.)")
        return
    end
    CharDBExecute("UPDATE basic_718_souls SET soul = " .. soul.guid .. ", soul_account = " .. account .. ", holding_account = " .. holding_id
        .. ", state = " .. STATE_GIVEN .. ", changed = UNIX_TIMESTAMP() WHERE dk = " .. player:GetGUIDLow())
    hold_selection(player, false)                   -- everyone selectable again (164)
    player:SendBroadcastMessage(string.format("Sargobras says: %s, for the Lich King. You, for the living. Off you go. "
        .. "(%d profession skills and %d recipes carried over.)", soul.name, skills, learned))
    -- the four buddies a death knight gets, at this moment and no other (617b)
    if BuddiesGiveDeathKnightBuddies then BuddiesGiveDeathKnightBuddies(player)
    else print("[death-knight-souls] ERROR: sargobras.lua isn't loaded; " .. player:GetName() .. " got no buddies (its next login gives them)") end
    return true
end
-- }}}

-- {{{ local function death_knight_look
-- A death knight skin and face for the soul's race and sex: the death
-- knight's own when they match, else a random one of that race's. nil for
-- races with none (undead: already undead).
local function death_knight_look(race, gender, dk_race, dk_gender, dk_skin, dk_face)
    if race == dk_race and gender == dk_gender then return dk_skin, dk_face end
    local by_race = DATA.death_knight_looks[race]
    local looks = by_race and by_race[gender]
    if not looks or #looks == 0 then return nil end
    local look = looks[math.random(#looks)]
    return look.skin, look.faces[math.random(#look.faces)]
end
-- }}}

-- {{{ local function take_back
-- Erase the death knight (it is kicked first), then, once the erase has
-- landed, move the soul home wearing a death knight's skin and face.
local function take_back(player, row)
    local dk_guid, dk_name = player:GetGUIDLow(), player:GetName()
    local me = CharDBQuery("SELECT race, gender, skin, face FROM characters WHERE guid = " .. dk_guid)
    local soul = CharDBQuery("SELECT name, race, gender FROM characters WHERE guid = " .. row.soul)
    local home = AuthDBQuery("SELECT username FROM account WHERE id = " .. row.soul_account)
    if not me or not soul or not home then
        print("[death-knight-souls] ERROR: cannot return the soul of " .. dk_name .. " (death knight, soul or home account row missing)")
        player:SendBroadcastMessage("Sargobras says: I can't find that soul. (The server log says why.)")
        return
    end
    local soul_name, race, gender = soul:GetString(0), soul:GetUInt32(1), soul:GetUInt32(2)
    local skin, face = death_knight_look(race, gender, me:GetUInt32(0), me:GetUInt32(1), me:GetUInt32(2), me:GetUInt32(3))
    local home_name = home:GetString(0)
    CharDBExecute("UPDATE basic_718_souls SET state = " .. STATE_RETURNING .. ", changed = UNIX_TIMESTAMP() WHERE dk = " .. dk_guid)
    player:SendBroadcastMessage("Sargobras says: As you wish. " .. soul_name .. " walks again. Mostly.")
    CreateLuaEvent(function()
        RunCommand(".character erase " .. dk_name)
        -- the erase command skips the character-delete event the buddy
        -- module listens to, so its buddies go here: their hidden account
        -- (deleting it deletes them) and the clan's rows (617a2)
        RunCommand(".account delete BUDDY" .. dk_guid)
        CharDBExecute("DELETE FROM buddy_roster WHERE owner = " .. dk_guid)
        CharDBExecute("DELETE FROM buddy_clan WHERE owner = " .. dk_guid)
    end, 1000, 1)
    CreateLuaEvent(function()
        RunCommand(".character changeaccount " .. home_name .. " " .. soul_name)
        if skin then
            CharDBExecute("UPDATE characters SET skin = " .. skin .. ", face = " .. face .. " WHERE guid = " .. row.soul)
        end
        CharDBExecute("DELETE FROM basic_718_souls WHERE dk = " .. dk_guid)
    end, 1000 + RETURN_DELAY_MS, 1)
end
-- }}}

-- {{{ local function on_hello
local function on_hello(event, player, creature)
    player:GossipClearMenu()
    local row = player:GetClass() == CLASS_DEATH_KNIGHT and ledger(player:GetGUIDLow()) or nil
    if row and row.state == STATE_OWED then
        -- no clan yet: the trade's pop-up also asks the clan's name (617l;
        -- the four buddies it brings are the clan)
        local ask_name = not player:IsInGuild() and BuddiesClanPopup ~= nil
        for _, c in ipairs(candidates(player)) do
            local confirm = string.format("Give %s to the Lich King? %s leaves your character list; you can ask for them back here later.", c.name, c.name)
            player:GossipMenuAddItem(GOSSIP_ICON_CHAT, string.format("Give %s (level %d) to the Lich King.", c.name, c.level), 0, c.guid, ask_name,
                ask_name and (confirm .. " " .. BuddiesClanPopup) or confirm)
        end
        player:GossipSendMenu(TEXT_OWED, creature)
    elseif row and row.state == STATE_GIVEN then
        if intro_done(player) then                   -- only once Acherus's chain is done
            player:GossipMenuAddItem(GOSSIP_ICON_CHAT, "I want my old life back.", 0, INTID_RETURN, false,
                "This death knight will be erased for good, and your old self returns to your character list, undead-pale. Are you sure?")
        end
        if not player:IsInGuild() and BuddiesClanPopup then
            player:GossipMenuAddItem(GOSSIP_ICON_CHAT, "Let me name our clan.", 0, INTID_CLAN, true, BuddiesClanPopup)
        end
        player:GossipSendMenu(TEXT_GIVEN, creature)
    else
        player:GossipSendMenu(TEXT_OTHER, creature)
    end
end
-- }}}

-- {{{ local function on_select
local function on_select(event, player, creature, sender, intid, code)
    player:GossipComplete()
    local row = player:GetClass() == CLASS_DEATH_KNIGHT and ledger(player:GetGUIDLow()) or nil
    if not row then return end
    if row.state == STATE_GIVEN and intid == INTID_RETURN then
        if intro_done(player) then take_back(player, row) end    -- the menu only offers it then; checked again here
    elseif row.state == STATE_GIVEN and intid == INTID_CLAN then
        if BuddiesTryClanName then BuddiesTryClanName(player, creature, code) end
    elseif row.state == STATE_OWED and intid ~= INTID_RETURN and intid ~= INTID_CLAN then
        if give_soul(player, intid) then
            if BuddiesTryClanName then BuddiesTryClanName(player, creature, code) end
            vanish(creature, player)
        end
    end
end
-- }}}

-- {{{ local function on_lich_king_hello
-- The Lich King gives no first quest to a death knight that still owes a
-- soul (Ritz, 2026-09-29: "The Lich King just, shouldn't give the player
-- the first quest until Sargobras is dealt with"). Returning true replaces
-- his quest menu (the Lua engine's gossip hook runs before the default);
-- returning false lets it through: a paid-up or pre-rule death knight, and
-- anyone else, gets his quests as normal.
local function on_lich_king_hello(event, player, creature)
    if player:GetClass() ~= CLASS_DEATH_KNIGHT then return false end
    local row = ledger(player:GetGUIDLow())
    if not row or row.state ~= STATE_OWED then return false end
    creature:SendUnitWhisper("You still carry a life that is not mine. Settle it with Sargobras, and then I will have work for you.", 0, player)
    player:GossipComplete()
    return true
end
-- }}}

-- {{{ local function on_first_login
-- Every death knight made from now on owes a soul, except a buddy: a
-- death-knight owner's buddies are death knights made by the buddy module
-- (617a3) on the owner's companion account, and they follow the owner out
-- of Acherus rather than paying their own way. A buddy is a character
-- named in buddy_roster (its row is filled before it first logs in).
local function on_first_login(event, player)
    if player:GetClass() ~= CLASS_DEATH_KNIGHT then return end
    if CharDBQuery("SELECT 1 FROM buddy_roster WHERE buddy = " .. player:GetGUIDLow()) then return end
    CharDBExecute("INSERT IGNORE INTO basic_718_souls (dk, state, changed) VALUES (" .. player:GetGUIDLow() .. ", " .. STATE_OWED .. ", UNIX_TIMESTAMP())")
    hold_selection(player, true)                    -- the row is still being written: held directly
end
-- }}}

-- {{{ local function on_login
-- The gate, and an owing death knight's selection held again (the rule is
-- in memory only and ends at logout).
local function on_login(event, player)
    check_gate(player, player:GetAreaId())
    if player:GetClass() ~= CLASS_DEATH_KNIGHT then return end
    local row = ledger(player:GetGUIDLow())
    if row and row.state == STATE_OWED then hold_selection(player, true)
    elseif row and row.state == STATE_GIVEN then hide_from(player) end   -- he went up in flame for them
end
-- }}}

RegisterPlayerEvent(PLAYER_EVENT_ON_FIRST_LOGIN, on_first_login)
RegisterPlayerEvent(PLAYER_EVENT_ON_LEARN_SPELL, on_learn_spell)
RegisterPlayerEvent(PLAYER_EVENT_ON_LOGIN, on_login)
RegisterPlayerEvent(PLAYER_EVENT_ON_UPDATE_ZONE, function(event, player, new_zone, new_area) check_gate(player, new_area) end)
-- an area change inside one zone (the necropolis to Death's Breach below it,
-- both zone 4298) fires no zone event, so the gate listens for areas too
RegisterPlayerEvent(PLAYER_EVENT_ON_UPDATE_AREA, function(event, player, old_area, new_area) check_gate(player, new_area) end)
RegisterCreatureGossipEvent(LICH_KING, GOSSIP_EVENT_ON_HELLO, on_lich_king_hello)
RegisterCreatureGossipEvent(SARGOBRAS, GOSSIP_EVENT_ON_HELLO,  on_hello)
RegisterCreatureGossipEvent(SARGOBRAS, GOSSIP_EVENT_ON_SELECT, on_select)
