--------------------------------------------------------------------------------
-- death-knight-souls.lua (issue 718, layer 1: the sacrifice)
--
-- On basic a death knight is what one of the player's heroes became. Ritz,
-- 2026-09-23: "When you create a DK it deletes that level 55 character that
-- you leveled to that level." And 2026-09-25: "Can we have a static
-- Sargobras who offers to help them leave Acherus in exchange for a powerful
-- soul? One hero for the Lich King, one death knight for the living..."
--
--   1. The ledger: a new death knight's first login writes an "owed" row
--      (characters database, basic_718_souls, E041). A death knight made
--      before this rule has no row and is never held.
--   2. The gate: an owing death knight who reaches anywhere but Acherus
--      (map 609) or the Ebon Hold (map 0, area 4281) is sent back to
--      Sargobras (spawned by 25-death-knight-sargobras, E040).
--   3. The trade: Sargobras lists the account's characters at level 55 or
--      higher ("level 55 or greater"), death knights left out. The chosen
--      one moves to a hidden holding account ("put into a holding area
--      in-case they change their mind"), one per player account, since an
--      account holds at most 10 characters per realm. The death knight
--      learns its professions ("inherit the professions of the character
--      it sacrificed") and may leave.
--   4. The undo: "Sargobras in Acherus can reverse this at any time,
--      deleting the death knight and returning the player character to
--      their account. They will be exactly the same except they will have
--      the DK haunted eyes and skin color and such because they are
--      canonically undead now. Sucks to be them..."
--
-- Moving characters between accounts and erasing one are done with the
-- server's own console commands (.character changeaccount, .character
-- erase), which keep its cache of who owns what correct; a bare UPDATE
-- would leave that cache stale until a restart.
--------------------------------------------------------------------------------

-- {{{ local function script_dir
-- The directory this file sits in, so the data file is found wherever the
-- lua_scripts tree is linked from (as in outland-flights.lua).
local function script_dir()
    local src = debug.getinfo(1, "S").source
    return (src:sub(1, 1) == "@" and src:sub(2) or src):match("^(.*[/\\])") or "./"
end
-- }}}

-- generated by scripts/generate-basic-death-knight-soul-data from the client's files
local DATA = dofile(script_dir() .. "data/death-knight-soul-data.lua")

local GOSSIP_EVENT_ON_HELLO  = 1
local GOSSIP_EVENT_ON_SELECT = 2
local PLAYER_EVENT_ON_LOGIN       = 3
local PLAYER_EVENT_ON_UPDATE_ZONE = 27
local PLAYER_EVENT_ON_FIRST_LOGIN = 30
local GOSSIP_ICON_CHAT = 0

local CLASS_DEATH_KNIGHT = 6
local SARGOBRAS          = 7180001                  -- creature, from 25-death-knight-sargobras
local TEXT_OWED, TEXT_GIVEN, TEXT_OTHER = 7180001, 7180002, 7180003
local SOUL_MIN_LEVEL     = 55

-- where an owing death knight may be, and where it is sent back to
local ACHERUS_MAP        = 609                      -- the Scarlet Enclave: the whole intro chain
local EBON_HOLD_MAP      = 0
local EBON_HOLD_AREA     = 4281                     -- "Acherus: The Ebon Hold" over the Eastern Plaguelands
local SARGOBRAS_SPOT     = { map = 0, x = 2338.5, y = -5676.2, z = 382.3, o = 3.8 }   -- a step in front of him, facing him

local STATE_OWED, STATE_GIVEN, STATE_RETURNING = 0, 1, 2
local INTID_RETURN       = 1                        -- the undo; a soul's own intid is its guid (always far above 1)
local HOLDING_PREFIX     = "SOULS"                  -- holding account name: SOULS<player account id>
local RETURN_DELAY_MS    = 5000                     -- after the erase, before the soul is moved back (the erase's writes land first)

-- {{{ local function ledger
-- The death knight's row, or nil when it has none (never held).
local function ledger(dk_guid)
    local q = CharDBQuery("SELECT soul, soul_account, holding_account, state FROM basic_718_souls WHERE dk = " .. dk_guid)
    if not q then return nil end
    return { soul = q:GetUInt32(0), soul_account = q:GetUInt32(1), holding = q:GetUInt32(2), state = q:GetUInt32(3) }
end
-- }}}

-- {{{ local function allowed_here
-- An owing death knight may be anywhere in Acherus, or in the Ebon Hold.
local function allowed_here(player, area)
    local map = player:GetMapId()
    if map == ACHERUS_MAP then return true end
    return map == EBON_HOLD_MAP and (area == EBON_HOLD_AREA or player:GetAreaId() == EBON_HOLD_AREA)
end
-- }}}

-- {{{ local function check_gate
-- Owing (state 0) and outside: back to Sargobras. Given, returning, or no
-- row: free to go.
local function check_gate(player, area)
    if player:GetClass() ~= CLASS_DEATH_KNIGHT then return end
    local row = ledger(player:GetGUIDLow())
    if not row or row.state ~= STATE_OWED then return end
    if allowed_here(player, area) then return end
    local s = SARGOBRAS_SPOT
    player:Teleport(s.map, s.x, s.y, s.z, s.o)
    player:SendBroadcastMessage("Sargobras says: Not so fast. The living will want to know who you were. Come and tell me.")
end
-- }}}

-- {{{ local function holding_account
-- The player account's own holding account, made the first time it is
-- needed with a random password nobody keeps (so it can never be logged
-- into). Returns its id and name, or nil and a reason.
local function holding_account(account_id)
    local name = HOLDING_PREFIX .. account_id
    local q = AuthDBQuery("SELECT id FROM account WHERE username = '" .. name .. "'")
    if not q then
        local chars = "abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789"
        local pw = {}
        for i = 1, 16 do local k = math.random(#chars); pw[i] = chars:sub(k, k) end
        pw = table.concat(pw)
        RunCommand(".account create " .. name .. " " .. pw)
        q = AuthDBQuery("SELECT id FROM account WHERE username = '" .. name .. "'")
        if not q then return nil, "the holding account " .. name .. " could not be created" end
    end
    return q:GetUInt32(0), name
end
-- }}}

-- {{{ local function candidates
-- The account's characters at level 55 or higher, death knights left out.
local function candidates(player)
    local q = CharDBQuery("SELECT guid, name, level FROM characters WHERE account = " .. player:GetAccountId()
        .. " AND level >= " .. SOUL_MIN_LEVEL .. " AND class <> " .. CLASS_DEATH_KNIGHT
        .. " AND guid <> " .. player:GetGUIDLow() .. " AND deleteInfos_Account IS NULL ORDER BY level DESC, name")
    local out = {}
    if q then
        repeat
            out[#out + 1] = { guid = q:GetUInt32(0), name = q:GetString(1), level = q:GetUInt32(2) }
        until not q:NextRow()
    end
    return out
end
-- }}}

-- {{{ local function carry_professions
-- Teach the death knight the soul's professions: the recipes and rank
-- spells first (a rank spell opens the skill), then the skill values
-- exactly as the soul had them. Read before the soul moves accounts.
local function carry_professions(player, soul_guid)
    local learned, skills = 0, 0
    local q = CharDBQuery("SELECT spell FROM character_spell WHERE guid = " .. soul_guid)
    if q then
        repeat
            local spell = q:GetUInt32(0)
            if DATA.profession_spells[spell] and not player:HasSpell(spell) then
                player:LearnSpell(spell)
                learned = learned + 1
            end
        until not q:NextRow()
    end
    q = CharDBQuery("SELECT skill, value, max FROM character_skills WHERE guid = " .. soul_guid)
    if q then
        repeat
            local skill, value, max = q:GetUInt32(0), q:GetUInt32(1), q:GetUInt32(2)
            if DATA.professions[skill] then
                -- step: the rank the maximum belongs to (75 Apprentice = 1 ... 450 Grand Master = 6)
                player:SetSkill(skill, math.max(1, math.ceil(max / 75)), value, max)
                skills = skills + 1
            end
        until not q:NextRow()
    end
    return learned, skills
end
-- }}}

-- {{{ local function give_soul
local function give_soul(player, soul_guid)
    local account = player:GetAccountId()
    local soul
    for _, c in ipairs(candidates(player)) do if c.guid == soul_guid then soul = c end end
    if not soul then
        player:SendBroadcastMessage("Sargobras says: That one isn't yours to give, or isn't ready.")
        return
    end
    local holding_id, holding_name = holding_account(account)
    if not holding_id then
        print("[death-knight-souls] ERROR: " .. holding_name .. "; " .. player:GetName() .. " keeps its soul for now")
        player:SendBroadcastMessage("Sargobras says: Something's wrong on my end. Keep your soul a little longer. (The server log says why.)")
        return
    end
    local learned, skills = carry_professions(player, soul.guid)
    RunCommand(".character changeaccount " .. holding_name .. " " .. soul.name)
    local check = CharDBQuery("SELECT account FROM characters WHERE guid = " .. soul.guid)
    if not check or check:GetUInt32(0) ~= holding_id then
        print("[death-knight-souls] ERROR: moving " .. soul.name .. " to " .. holding_name .. " failed (is that account full?); "
            .. player:GetName() .. " keeps its soul for now")
        player:SendBroadcastMessage("Sargobras says: The soul slipped through my fingers. Try again later. (The server log says why.)")
        return
    end
    CharDBExecute("UPDATE basic_718_souls SET soul = " .. soul.guid .. ", soul_account = " .. account .. ", holding_account = " .. holding_id
        .. ", state = " .. STATE_GIVEN .. ", changed = UNIX_TIMESTAMP() WHERE dk = " .. player:GetGUIDLow())
    player:SendBroadcastMessage(string.format("Sargobras says: %s, for the Lich King. You, for the living. Off you go. "
        .. "(%d profession skills and %d recipes carried over.)", soul.name, skills, learned))
end
-- }}}

-- {{{ local function death_knight_look
-- A death knight skin and face for the soul's race and sex: the death
-- knight's own when they match, else a random one of that race's. nil for
-- races with none (undead: already undead).
local function death_knight_look(race, gender, dk_race, dk_gender, dk_skin, dk_face)
    if race == dk_race and gender == dk_gender then return dk_skin, dk_face end
    local by_race = DATA.death_knight_looks[race]
    local looks = by_race and by_race[gender]
    if not looks or #looks == 0 then return nil end
    local look = looks[math.random(#looks)]
    return look.skin, look.faces[math.random(#look.faces)]
end
-- }}}

-- {{{ local function take_back
-- Erase the death knight (it is kicked first), then, once the erase has
-- landed, move the soul home wearing a death knight's skin and face.
local function take_back(player, row)
    local dk_guid, dk_name = player:GetGUIDLow(), player:GetName()
    local me = CharDBQuery("SELECT race, gender, skin, face FROM characters WHERE guid = " .. dk_guid)
    local soul = CharDBQuery("SELECT name, race, gender FROM characters WHERE guid = " .. row.soul)
    local home = AuthDBQuery("SELECT username FROM account WHERE id = " .. row.soul_account)
    if not me or not soul or not home then
        print("[death-knight-souls] ERROR: cannot return the soul of " .. dk_name .. " (death knight, soul or home account row missing)")
        player:SendBroadcastMessage("Sargobras says: I can't find that soul. (The server log says why.)")
        return
    end
    local soul_name, race, gender = soul:GetString(0), soul:GetUInt32(1), soul:GetUInt32(2)
    local skin, face = death_knight_look(race, gender, me:GetUInt32(0), me:GetUInt32(1), me:GetUInt32(2), me:GetUInt32(3))
    local home_name = home:GetString(0)
    CharDBExecute("UPDATE basic_718_souls SET state = " .. STATE_RETURNING .. ", changed = UNIX_TIMESTAMP() WHERE dk = " .. dk_guid)
    player:SendBroadcastMessage("Sargobras says: As you wish. " .. soul_name .. " walks again. Mostly.")
    CreateLuaEvent(function()
        RunCommand(".character erase " .. dk_name)
    end, 1000, 1)
    CreateLuaEvent(function()
        RunCommand(".character changeaccount " .. home_name .. " " .. soul_name)
        if skin then
            CharDBExecute("UPDATE characters SET skin = " .. skin .. ", face = " .. face .. " WHERE guid = " .. row.soul)
        end
        CharDBExecute("DELETE FROM basic_718_souls WHERE dk = " .. dk_guid)
    end, 1000 + RETURN_DELAY_MS, 1)
end
-- }}}

-- {{{ local function on_hello
local function on_hello(event, player, creature)
    player:GossipClearMenu()
    local row = player:GetClass() == CLASS_DEATH_KNIGHT and ledger(player:GetGUIDLow()) or nil
    if row and row.state == STATE_OWED then
        for _, c in ipairs(candidates(player)) do
            player:GossipMenuAddItem(GOSSIP_ICON_CHAT, string.format("Give %s (level %d) to the Lich King.", c.name, c.level), 0, c.guid, false,
                string.format("Give %s to the Lich King? %s leaves your character list; you can ask for them back here later.", c.name, c.name))
        end
        player:GossipSendMenu(TEXT_OWED, creature)
    elseif row and row.state == STATE_GIVEN then
        player:GossipMenuAddItem(GOSSIP_ICON_CHAT, "I want my old life back.", 0, INTID_RETURN, false,
            "This death knight will be erased for good, and your old self returns to your character list, undead-pale. Are you sure?")
        player:GossipSendMenu(TEXT_GIVEN, creature)
    else
        player:GossipSendMenu(TEXT_OTHER, creature)
    end
end
-- }}}

-- {{{ local function on_select
local function on_select(event, player, creature, sender, intid)
    player:GossipComplete()
    local row = player:GetClass() == CLASS_DEATH_KNIGHT and ledger(player:GetGUIDLow()) or nil
    if not row then return end
    if row.state == STATE_GIVEN and intid == INTID_RETURN then
        take_back(player, row)
    elseif row.state == STATE_OWED and intid ~= INTID_RETURN then
        give_soul(player, intid)
    end
end
-- }}}

-- {{{ local function on_first_login
-- Every death knight made from now on owes a soul.
local function on_first_login(event, player)
    if player:GetClass() ~= CLASS_DEATH_KNIGHT then return end
    CharDBExecute("INSERT IGNORE INTO basic_718_souls (dk, state, changed) VALUES (" .. player:GetGUIDLow() .. ", " .. STATE_OWED .. ", UNIX_TIMESTAMP())")
end
-- }}}

RegisterPlayerEvent(PLAYER_EVENT_ON_FIRST_LOGIN, on_first_login)
RegisterPlayerEvent(PLAYER_EVENT_ON_LOGIN, function(event, player) check_gate(player, player:GetAreaId()) end)
RegisterPlayerEvent(PLAYER_EVENT_ON_UPDATE_ZONE, function(event, player, new_zone, new_area) check_gate(player, new_area) end)
RegisterCreatureGossipEvent(SARGOBRAS, GOSSIP_EVENT_ON_HELLO,  on_hello)
RegisterCreatureGossipEvent(SARGOBRAS, GOSSIP_EVENT_ON_SELECT, on_select)
