-- race-class-data.lua - GENERATED by scripts/generate-basic-race-class-data
-- from the world database's playercreateinfo and the client's ChrRaces/ChrClasses.dbc;
-- do not edit by hand (issue 617b).
--
-- races[race id]   = { name, team ("alliance"/"horde"), classes = { class id, ... } }
-- classes[class id] = { name }
return {
    races = {
        [1] = { name = "Human", team = "alliance", classes = { 1, 2, 4, 5, 6, 8, 9 } },
        [2] = { name = "Orc", team = "horde", classes = { 1, 3, 4, 6, 7, 9 } },
        [3] = { name = "Dwarf", team = "alliance", classes = { 1, 2, 3, 4, 5, 6 } },
        [4] = { name = "Night Elf", team = "alliance", classes = { 1, 3, 4, 5, 6, 11 } },
        [5] = { name = "Undead", team = "horde", classes = { 1, 4, 5, 6, 8, 9 } },
        [6] = { name = "Tauren", team = "horde", classes = { 1, 3, 6, 7, 11 } },
        [7] = { name = "Gnome", team = "alliance", classes = { 1, 4, 6, 8, 9 } },
        [8] = { name = "Troll", team = "horde", classes = { 1, 3, 4, 5, 6, 7, 8 } },
        [10] = { name = "Blood Elf", team = "horde", classes = { 2, 3, 4, 5, 6, 8, 9 } },
        [11] = { name = "Draenei", team = "alliance", classes = { 1, 2, 3, 5, 6, 7, 8 } },
    },
    classes = {
        [1] = { name = "Warrior" },
        [2] = { name = "Paladin" },
        [3] = { name = "Hunter" },
        [4] = { name = "Rogue" },
        [5] = { name = "Priest" },
        [6] = { name = "Death Knight" },
        [7] = { name = "Shaman" },
        [8] = { name = "Mage" },
        [9] = { name = "Warlock" },
        [11] = { name = "Druid" },
    },
}
