-- MARKER_E025_APPLY basic-valley-universal-trainers
-- ============================================================================
-- 10-valley-universal-trainers.sql (issue 155e) — APPLY SOURCE
-- ============================================================================
-- One "Visiting Mentor" at each place the stock world sends new characters
-- to train: every race's starting valley, first town and capital (24 sites,
-- marked in stock data by stacks of placeholder NPCs). Each teaches the
-- classes that have no trainer at its site, one dialogue line per class:
-- "Can you teach me the ways of the druid?" opens the druid list. A player
-- sees only the line for their own class (the server hides a trainer line
-- whose list is for another class); a player whose class is trained at the
-- site sees only the greeting. One mentor per site, never two.
--
-- Mechanism:
--   * Nine class trainer lists (trainer ids 155101-155111, id = 155100 +
--     class), each the union of that class's stock lists (trainer.Type 0,
--     Requirement = class), with the stock class requirement kept.
--   * Each mentor has no trainer list of its own; its gossip menu has one
--     trainer line per missing class whose ActionMenuID names that class's
--     list. Source patch B029 makes the server honour that (the stock server
--     already does the same for vendor lines).
--   * Sites, missing classes and looks come from the GENERATED block below,
--     written by scripts/generate-basic-mentor-hubs from stock data: the
--     placeholder stacks give the sites, the real class trainers around each
--     site give the classes present, and each mentor borrows the look of a
--     level 50+ trainer of a missing class from elsewhere in its faction
--     (owner: "a powerful level 40ish trainer's model ... so they feel a bit
--     more thematic"); the eight starting valleys use looks picked with the
--     owner, e.g. a tauren druid on Sunstrider Isle.
--   * The placeholder NPCs (entries 26324-26332, goblin "Druid Trainer",
--     "Warrior Trainer", ...) at each site are removed and the mentor stands
--     where they stood (owner: "instead of the placeholder goblin"). Their
--     rows are saved for the revert.
--
-- Id ranges owned by this file (checked free in stock data 2026-09-23):
--   trainer.Id                      155101-155111  (class lists)
--   npc_text.ID, gossip_menu.MenuID 155001-155024  (one per site)
--   creature_template.entry         1550001-1550024
--   creature.guid                   15500001-15500024
--
-- Schema note: creature.id, not id1 (renamed upstream in 2026_06_16_00).
-- Database: acore_world_basic. Re-applicable: every owned row is deleted
-- first; the goblin backup uses INSERT IGNORE. Applied by E025.
-- ============================================================================

-- ---- mentor sites (generated) -------------------------------------------
-- One row per site that lacks at least one class: where the placeholders
-- stood (the mentor stands there), and whose look it borrows. The missing
-- classes per site are computed by the generator from the real class
-- trainers around each site. Re-run scripts/generate-basic-mentor-hubs to
-- regenerate the block below; never edit it by hand.
CREATE TABLE IF NOT EXISTS `basic_155e_hubs` (
  `hub`        tinyint unsigned  NOT NULL,
  `name`       varchar(32)       NOT NULL,
  `map`        smallint unsigned NOT NULL,
  `x` float NOT NULL, `y` float NOT NULL, `z` float NOT NULL, `o` float NOT NULL,
  `clone_from` int unsigned      NOT NULL,
  `clone_note` varchar(96)       NOT NULL,
  PRIMARY KEY (`hub`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='issue 155e: Visiting Mentor sites';
CREATE TABLE IF NOT EXISTS `basic_155e_missing` (
  `hub`   tinyint unsigned NOT NULL,
  `class` tinyint unsigned NOT NULL,
  PRIMARY KEY (`hub`, `class`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='issue 155e: classes each site lacks';
DROP TABLE IF EXISTS `basic_155e_valleys`;   -- the valleys-only first version's table

-- >>> GENERATED BY scripts/generate-basic-mentor-hubs BEGIN (do not edit by hand)
-- sites: 24 placeholder clusters; a site with no missing class gets no mentor
DELETE FROM `basic_155e_hubs`;
INSERT INTO `basic_155e_hubs` (`hub`, `name`, `map`, `x`, `y`, `z`, `o`, `clone_from`, `clone_note`) VALUES
  ( 1, 'Ammen Vale', 530, -4076.080, -13752.800, 78.557, 4.7298, 5165, 'Hulfdan Blackbeard, rogue trainer'),
  ( 2, 'Azure Watch', 530, -4160.230, -12529.500, 49.180, 2.0944, 918, 'Osborne the Night Man, rogue trainer'),
  ( 3, 'Bloodhoof Village', 1, -2286.500, -360.229, -5.658, 2.7053, 3046, 'Father Cobb, priest trainer'),
  ( 4, 'Brill', 0, 2252.920, 308.318, 38.765, 5.2185, 3039, 'Holt Thunderhorn, hunter trainer'),
  ( 5, 'Camp Narache', 1, -2909.630, -244.459, 56.765, 5.2709, 3047, 'Archmage Shymm, mage trainer'),
  ( 6, 'Coldridge Valley', 0, -6188.090, 392.323, 397.086, 4.7473, 17519, 'Hobahken, shaman trainer'),
  ( 7, 'Darnassus', 1, 9999.290, 2285.660, 1345.160, 4.5030, 5173, 'Alexander Calder, warlock trainer'),
  ( 8, 'Deathknell', 0, 1822.940, 1585.590, 99.149, 1.2392, 20406, 'Champion Cyssa Dawnrose, paladin trainer'),
  ( 9, 'Dolanaar', 1, 9856.330, 954.043, 1310.540, 0.7505, 35281, 'Rukua, paladin trainer'),
  (10, 'Falconwing Square', 530, 9547.040, -6812.600, 20.227, 3.4383, 3344, 'Kardris Dreamseeker, shaman trainer'),
  (11, 'Goldshire', 0, -9496.100, 35.965, 60.407, 2.4085, 4138, 'Jeen''ra Nightrunner, hunter trainer'),
  (12, 'Ironforge', 0, -4941.620, -996.549, 505.210, 2.0071, 5504, 'Sheldras Moontree, druid trainer'),
  (13, 'Kharanos', 0, -5575.260, -485.474, 401.292, 1.6406, 17204, 'Farseer Nobundo, shaman trainer'),
  (14, 'Northshire Valley', 0, -8946.190, -158.145, 85.686, 1.6406, 4217, 'Mathrengyl Bearwalker, druid trainer'),
  (15, 'Orgrimmar', 1, 1568.310, -4420.210, 10.915, 4.2586, 16655, 'Harene Plainwalker, druid trainer'),
  (16, 'Razor Hill', 1, 257.529, -4747.890, 13.869, 1.0996, 4566, 'Kaelystia Hatebringer, mage trainer'),
  (17, 'Shadowglen', 1, 10315.700, 852.533, 1334.570, 5.6549, 5147, 'Valgar Highforge, paladin trainer'),
  (18, 'Silvermoon City', 530, 9560.710, -7320.980, 17.892, 4.1190, 3042, 'Sark Ragetotem, warrior trainer'),
  (19, 'Sunstrider Isle', 530, 10377.400, -6400.490, 53.482, 5.9690, 3034, 'Sheal Runetotem, druid trainer'),
  (20, 'The Exodar', 530, -4034.340, -11891.900, 2.159, 4.7996, 461, 'Demisette Cloyce, warlock trainer'),
  (21, 'Thunder Bluff', 1, -1280.320, 87.038, 132.570, 0.6981, 3401, 'Shenthul, rogue trainer'),
  (22, 'Undercity', 0, 1811.610, 194.030, 74.166, 1.6406, 3032, 'Beram Skychaser, shaman trainer'),
  (23, 'Valley of Trials', 1, -622.560, -4220.120, 41.901, 5.6898, 23128, 'Master Pyreanor, paladin trainer');
DELETE FROM `basic_155e_missing`;
INSERT INTO `basic_155e_missing` (`hub`, `class`) VALUES
  (1, 4), (1, 9), (1, 11), (2, 4), (2, 9), (2, 11), (3, 2), (3, 4), (3, 5), (3, 8), (3, 9), (4, 2), (4, 3), (4, 7), (4, 11), (5, 2), (5, 4), (5, 5), (5, 8), (5, 9), (6, 7), (6, 11), (7, 7), (7, 9), (8, 2), (8, 3), (8, 7), (8, 11), (9, 2), (9, 7), (9, 8), (9, 9), (10, 1), (10, 7), (10, 11), (11, 3), (11, 7), (11, 11), (12, 11), (13, 7), (13, 11), (14, 3), (14, 7), (14, 11), (15, 11), (16, 2), (16, 8), (16, 11), (17, 2), (17, 7), (17, 8), (17, 9), (18, 1), (18, 7), (19, 1), (19, 7), (19, 11), (20, 4), (20, 9), (21, 2), (21, 4), (21, 9), (22, 3), (22, 7), (22, 11), (23, 2), (23, 11);
-- <<< GENERATED BY scripts/generate-basic-mentor-hubs END

-- ---- clear everything this file owns (re-applicable) -----------------------
DELETE FROM `creature`                  WHERE `guid`       BETWEEN 15500001 AND 15500024;
DELETE FROM `creature_template_model`   WHERE `CreatureID` BETWEEN 1550001  AND 1550024;
DELETE FROM `creature_template`         WHERE `entry`      BETWEEN 1550001  AND 1550024;
DELETE FROM `gossip_menu_option`        WHERE `MenuID`     BETWEEN 155001   AND 155024;
DELETE FROM `gossip_menu`               WHERE `MenuID`     BETWEEN 155001   AND 155024;
DELETE FROM `npc_text`                  WHERE `ID`         BETWEEN 155001   AND 155024;
DELETE FROM `trainer_spell`             WHERE `TrainerId`  BETWEEN 155101   AND 155111;
DELETE FROM `trainer`                   WHERE `Id`         BETWEEN 155101   AND 155111;

-- ---- one trainer list per class (the stock class gate stays on) ------------
INSERT INTO `trainer` (`Id`, `Type`, `Requirement`, `Greeting`)
SELECT DISTINCT 155100 + m.`class`, 0, m.`class`, 'Here is what I can teach you.'
FROM `basic_155e_missing` m;

INSERT INTO `trainer_spell`
  (`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`,
   `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`)
SELECT 155100 + t.`Requirement`, ts.`SpellId`,
       MIN(ts.`MoneyCost`), MIN(ts.`ReqSkillLine`), MIN(ts.`ReqSkillRank`),
       MIN(ts.`ReqAbility1`), MIN(ts.`ReqAbility2`), MIN(ts.`ReqAbility3`), MIN(ts.`ReqLevel`)
FROM `trainer` t
JOIN `trainer_spell` ts ON ts.`TrainerId` = t.`Id`
WHERE t.`Type` = 0
  AND t.`Id` NOT BETWEEN 155101 AND 155111
  AND t.`Requirement` IN (SELECT DISTINCT `class` FROM `basic_155e_missing`)
GROUP BY t.`Requirement`, ts.`SpellId`;

-- ---- dialogue: greeting + one trainer line per missing class ---------------
INSERT INTO `npc_text` (`ID`, `text0_0`, `lang0`, `Probability0`)
SELECT 155000 + v.`hub`,
       CONCAT('Not every calling has a teacher in ', v.`name`,
              '. If yours is one of them, I can help. If not, your own trainers are close by.'),
       0, 1
FROM `basic_155e_hubs` v;

INSERT INTO `gossip_menu` (`MenuID`, `TextID`)
SELECT 155000 + v.`hub`, 155000 + v.`hub` FROM `basic_155e_hubs` v;

-- OptionType 5 = GOSSIP_OPTION_TRAINER, OptionNpcFlag 16 = UNIT_NPC_FLAG_TRAINER,
-- OptionIcon 3 = trainer book. ActionMenuID = the class's list (B029).
INSERT INTO `gossip_menu_option`
  (`MenuID`, `OptionID`, `OptionIcon`, `OptionText`, `OptionBroadcastTextID`,
   `OptionType`, `OptionNpcFlag`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxText`, `BoxBroadcastTextID`)
SELECT 155000 + m.`hub`, m.`class`, 3,
       CONCAT('Can you teach me the ways of the ',
              ELT(m.`class`, 'warrior', 'paladin', 'hunter', 'rogue', 'priest', 'death knight',
                            'shaman', 'mage', 'warlock', '', 'druid'), '?'),
       0, 5, 16, 155100 + m.`class`, 0, 0, 0, '', 0
FROM `basic_155e_missing` m;

-- ---- NPC templates: copies of each site's borrowed look --------------------
DROP TEMPORARY TABLE IF EXISTS `tmp_155e_template`;
CREATE TEMPORARY TABLE `tmp_155e_template` AS
SELECT t.* FROM `creature_template` t JOIN `basic_155e_hubs` v ON v.`clone_from` = t.`entry`;
UPDATE `tmp_155e_template` t JOIN `basic_155e_hubs` v ON v.`clone_from` = t.`entry`
SET t.`entry`              = 1550000 + v.`hub`,
    t.`difficulty_entry_1` = 0, t.`difficulty_entry_2` = 0, t.`difficulty_entry_3` = 0,
    t.`KillCredit1`        = 0, t.`KillCredit2` = 0,
    t.`name`               = 'Visiting Mentor',
    t.`subname`            = 'Class Trainer',
    t.`gossip_menu_id`     = 155000 + v.`hub`,
    t.`npcflag`            = 1 | 16,           -- UNIT_NPC_FLAG_GOSSIP | UNIT_NPC_FLAG_TRAINER
    t.`lootid`             = 0, t.`pickpocketloot` = 0, t.`skinloot` = 0,
    t.`AIName`             = '',
    t.`ScriptName`         = '';
INSERT INTO `creature_template` SELECT * FROM `tmp_155e_template`;
DROP TEMPORARY TABLE `tmp_155e_template`;

DROP TEMPORARY TABLE IF EXISTS `tmp_155e_model`;
CREATE TEMPORARY TABLE `tmp_155e_model` AS
SELECT m.* FROM `creature_template_model` m JOIN `basic_155e_hubs` v ON v.`clone_from` = m.`CreatureID`;
UPDATE `tmp_155e_model` m JOIN `basic_155e_hubs` v ON v.`clone_from` = m.`CreatureID`
SET m.`CreatureID` = 1550000 + v.`hub`;
INSERT INTO `creature_template_model` SELECT * FROM `tmp_155e_model`;
DROP TEMPORARY TABLE `tmp_155e_model`;

-- ---- remove the placeholders at each site (saved for the revert) ----------
CREATE TABLE IF NOT EXISTS `basic_155e_goblin_backup` LIKE `creature`;
INSERT IGNORE INTO `basic_155e_goblin_backup`
SELECT c.* FROM `creature` c
JOIN `basic_155e_hubs` v ON v.`map` = c.`map`
WHERE c.`id` BETWEEN 26324 AND 26332
  AND POW(c.`position_x` - v.`x`, 2) + POW(c.`position_y` - v.`y`, 2) < 60 * 60;   -- a site's stack stands within a few yards
DELETE c FROM `creature` c
JOIN `basic_155e_goblin_backup` b ON b.`guid` = c.`guid`;

-- ---- spawns: where each site's placeholders stood ------------------------
INSERT INTO `creature`
  (`guid`, `id`, `map`, `spawnMask`, `phaseMask`,
   `position_x`, `position_y`, `position_z`, `orientation`,
   `spawntimesecs`, `Comment`)
SELECT 15500000 + v.`hub`, 1550000 + v.`hub`, v.`map`, 1, 1,
       v.`x`, v.`y`, v.`z`, v.`o`,
       300, CONCAT('issue 155e: Visiting Mentor, ', v.`name`, ' (looks like ', v.`clone_note`, ')')
FROM `basic_155e_hubs` v;

-- ============================================================================
-- End of 10-valley-universal-trainers.sql (apply)
-- ============================================================================
