-- MARKER_E028_APPLY basic-outland-without-quests
-- ============================================================================
-- 13-outland-without-quests.sql (issue 155l) — APPLY SOURCE
-- ============================================================================
-- Ritz, 2026-09-24: "we should remove all quests in Outland. Not
-- questgivers, but quests. Players make their own missions and rewards,
-- they've graduated from quests." The Isle of Quel'Danas's quests too
-- ("They all require level 70 anyway"), and the Shattrath portal to the Isle
-- is removed ("remove"), so the Light's Hope flight (outland-flights.lua)
-- is the only way there.
--
-- How: every such quest gets a row in the server's `disables` table
-- (sourceType 1 = quest), which makes it unobtainable and hides it from
-- givers; the givers stay in the world, and quest items stay in loot (Ritz:
-- "they are unobtainable if the quests cannot be claimed"). The revert
-- deletes exactly the rows this file added.
--
-- Which quests: filed under an Outland area (its zones, Shattrath, the
-- Isle, any place inside them, any Outland dungeon or raid, Magisters'
-- Terrace: the GENERATED list), or started or ended by a creature or object
-- standing in Outland or one of those instances. Quests that already had a
-- disables row are left as they are.
--
-- "Outland" as spawn position: as in 12-outland-without-tradeskills.sql.
-- Database: acore_world_basic. Applied by E028.
-- ============================================================================

DROP TABLE IF EXISTS `tmp_155l_areas`;
CREATE TABLE `tmp_155l_areas` (`area_id` int unsigned NOT NULL, PRIMARY KEY (`area_id`));
-- >>> GENERATED by scripts/generate-basic-outland-quests-sql — do not edit by hand
-- Outland's zones, Shattrath, the Isle, every area inside them, and every area on an Outland instance map: 379
INSERT INTO `tmp_155l_areas` (`area_id`) VALUES (3483),(3518),(3519),(3520),(3521),(3522),(3523),(3535),(3536),(3538),(3539),(3541),(3542),(3543),(3544),(3545),(3546),(3547),(3548),(3549),(3550),(3551),(3552),(3553),(3554),(3555),(3556),(3562),(3563),(3565),(3582),(3607),(3609),(3610),(3611),(3613),(3614),(3615),(3616),(3617),(3618),(3619),(3620),(3621),(3622),(3623),(3624),(3625),(3626),(3627),(3628),(3629),(3630),(3631),(3632),(3633),(3634),(3635),(3636),(3637),(3638),(3640),(3641),(3642),(3643),(3644),(3645),(3646),(3647),(3648),(3649),(3650),(3651),(3652),(3653),(3654),(3655),(3656),(3657),(3658),(3659),(3660),(3661),(3666),(3667),(3668),(3669),(3670),(3671),(3672),(3673),(3674),(3675),(3676),(3677),(3678),(3679),(3680),(3681),(3682),(3683),(3684),(3685),(3686),(3687),(3688),(3689),(3690),(3691),(3692),(3693),(3694),(3695),(3696),(3697),(3699),(3700),(3701),(3703),(3705),(3712),(3713),(3714),(3715),(3716),(3717),(3718),(3719),(3720),(3721),(3722),(3723),(3724),(3725),(3726),(3727),(3728),(3729),(3730),(3731),(3732),(3733),(3734),(3735),(3736),(3737),(3738),(3739),(3740),(3741),(3742),(3743),(3744),(3745),(3746),(3747),(3748),(3749),(3750),(3751),(3752),(3753),(3754),(3755),(3756),(3757),(3758),(3759),(3760),(3761),(3762),(3763),(3764),(3765),(3766),(3767),(3768),(3769),(3770),(3771),(3772),(3773),(3774),(3775),(3776),(3777),(3778),(3779),(3780),(3781),(3782),(3783),(3784),(3785),(3786),(3787),(3788),(3789),(3790),(3791),(3792),(3793),(3794),(3795),(3796),(3797),(3798),(3799),(3800),(3801),(3802),(3803),(3804),(3806),(3807),(3808),(3809),(3810),(3811),(3812),(3813),(3814),(3815),(3816),(3818),(3819),(3821),(3822),(3824),(3825),(3826),(3827),(3828),(3829),(3830),(3831),(3832),(3833),(3834),(3835),(3836),(3837),(3838),(3839),(3840),(3841),(3842),(3844),(3845),(3847),(3848),(3849),(3850),(3851),(3852),(3854),(3855),(3858),(3859),(3860),(3862),(3863),(3864),(3865),(3866),(3867),(3868),(3873),(3874),(3875),(3876),(3877),(3878),(3879),(3880),(3881),(3882),(3883),(3884),(3885),(3886),(3887),(3888),(3889),(3890),(3891),(3892),(3893),(3894),(3895),(3896),(3897),(3898),(3899),(3900),(3901),(3902),(3903),(3904),(3905),(3918),(3919),(3920),(3921),(3922),(3923),(3924),(3925),(3926),(3927),(3928),(3929),(3930),(3931),(3932),(3933),(3934),(3935),(3936),(3937),(3938),(3939),(3940),(3941),(3942),(3943),(3944),(3945),(3946),(3947),(3949),(3950),(3951),(3952),(3953),(3954),(3955),(3956),(3957),(3958),(3959),(3960),(3961),(3962),(3963),(3964),(3965),(3966),(3967),(3969),(3970),(3971),(3972),(3973),(3974),(3975),(3976),(3977),(3978),(4008),(4009),(4078),(4080),(4081),(4082),(4083),(4084),(4085),(4086),(4087),(4088),(4089),(4090),(4091),(4092),(4093),(4094),(4095),(4131);
-- <<< GENERATED END

DROP TABLE IF EXISTS `tmp_155l_maps`;
CREATE TABLE `tmp_155l_maps` (`map_id` int unsigned NOT NULL, PRIMARY KEY (`map_id`));
INSERT INTO `tmp_155l_maps` VALUES (540),(542),(543),(544),(545),(546),(547),(548),(550),(552),(553),(554),(555),(556),(557),(558),(564),(565),(585);

DROP TABLE IF EXISTS `tmp_155l_quests`;
CREATE TABLE `tmp_155l_quests` (`id` int unsigned NOT NULL, PRIMARY KEY (`id`));
INSERT IGNORE INTO `tmp_155l_quests`
SELECT q.`ID` FROM `quest_template` q WHERE q.`QuestSortID` > 0 AND q.`QuestSortID` IN (SELECT `area_id` FROM `tmp_155l_areas`);
INSERT IGNORE INTO `tmp_155l_quests`
SELECT s.`quest` FROM `creature_queststarter` s JOIN `creature` c ON c.`id` = s.`id`
WHERE (c.`map` = 530 AND (c.`position_y` > -2000 OR c.`position_x` > 11350)) OR c.`map` IN (SELECT `map_id` FROM `tmp_155l_maps`);
INSERT IGNORE INTO `tmp_155l_quests`
SELECT s.`quest` FROM `creature_questender` s JOIN `creature` c ON c.`id` = s.`id`
WHERE (c.`map` = 530 AND (c.`position_y` > -2000 OR c.`position_x` > 11350)) OR c.`map` IN (SELECT `map_id` FROM `tmp_155l_maps`);
INSERT IGNORE INTO `tmp_155l_quests`
SELECT s.`quest` FROM `gameobject_queststarter` s JOIN `gameobject` g ON g.`id` = s.`id`
WHERE (g.`map` = 530 AND (g.`position_y` > -2000 OR g.`position_x` > 11350)) OR g.`map` IN (SELECT `map_id` FROM `tmp_155l_maps`);
INSERT IGNORE INTO `tmp_155l_quests`
SELECT s.`quest` FROM `gameobject_questender` s JOIN `gameobject` g ON g.`id` = s.`id`
WHERE (g.`map` = 530 AND (g.`position_y` > -2000 OR g.`position_x` > 11350)) OR g.`map` IN (SELECT `map_id` FROM `tmp_155l_maps`);

-- which rows this file added, so the revert removes only those
CREATE TABLE IF NOT EXISTS `basic_155l_disabled` (
  `entry` int unsigned NOT NULL,
  PRIMARY KEY (`entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='issue 155l: quests this profile disabled (disables rows it added), for the revert';
INSERT IGNORE INTO `basic_155l_disabled` (`entry`)
SELECT q.`id` FROM `tmp_155l_quests` q
WHERE NOT EXISTS (SELECT 1 FROM `disables` d WHERE d.`sourceType` = 1 AND d.`entry` = q.`id`);
INSERT IGNORE INTO `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`)
SELECT 1, `entry`, 0, '', '', 'basic 155l: no quests in Outland' FROM `basic_155l_disabled`;

-- ---- the Shattrath portal to the Isle of Quel'Danas ---------------------------
CREATE TABLE IF NOT EXISTS `basic_155l_gameobject` LIKE `gameobject`;
INSERT IGNORE INTO `basic_155l_gameobject` SELECT * FROM `gameobject` WHERE `id` = 187056;   -- Shattrath Portal to Isle of Quel'Danas
DELETE FROM `gameobject` WHERE `id` = 187056;

DROP TABLE `tmp_155l_quests`;
DROP TABLE `tmp_155l_maps`;
DROP TABLE `tmp_155l_areas`;

-- ============================================================================
-- End of 13-outland-without-quests.sql (apply)
-- ============================================================================
