-- MARKER_E032_APPLY basic-outland-world-levels
-- ============================================================================
-- 17-outland-world-levels.sql (issue 155k) — APPLY SOURCE
-- ============================================================================
-- Outland's open-world monsters are four levels higher (six on the Isle of
-- Quel'Danas). Ritz, 2026-09-24: "I think we might need to give all the
-- monsters in Outland a +4 level bonus, because a level 58 normal mob
-- dropping raid gear semi-rarely is... too powerful." / the Isle: "+6".
--
-- Raised: creature templates that
--   * stand only in Outland or on the Isle (map 530, y > -2000 or x > 11350;
--     a template also spawned anywhere else is left alone, so nothing in
--     Azeroth or Eversong moves);
--   * no player befriends (their faction template is in the generated list
--     below: hostile, or neutral like Nagrand's talbuks; a reputation
--     faction's people only if every race starts Hostile with it);
--   * are not townsfolk: a neutral one has no gossip, quest, vendor,
--     trainer or other service flag at all; a hostile one may talk or give a
--     quest (the Enraged Spirits, the Wyrmcult do) but has no service flag
--     past those two (the Netherwing Ledge's vendors are hostile Dragonmaw
--     until disguised, and stay stock);
--   * are not world bosses (rank 3; 155j: stock), critters, or invisible
--     spell triggers, and are not one of 155f's dungeon templates.
-- +6 when every spawn of the template is on the Isle, otherwise +4.
-- Not raised: creatures that only ever appear by being summoned (they have
-- no spawn to place them in Outland). Loot, health and damage tables are
-- untouched; health, damage and armor follow the new level as for any
-- creature of that level.
-- Stock levels saved (basic_155k_level_backup); each apply first restores
-- them, so re-applying is exact.
-- Database: acore_world_basic. Applied by E032, after E024 (155f), whose
-- template list it reads.
-- ============================================================================

-- ---- 0. put back what an earlier apply changed -------------------------------------
CREATE TABLE IF NOT EXISTS `basic_155k_level_backup` (
  `entry`    int unsigned     NOT NULL,
  `minlevel` tinyint unsigned NOT NULL,
  `maxlevel` tinyint unsigned NOT NULL,
  PRIMARY KEY (`entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='issue 155k: stock levels of the raised Outland world creatures, for the revert';
UPDATE `creature_template` t JOIN `basic_155k_level_backup` b ON b.`entry` = t.`entry`
SET t.`minlevel` = b.`minlevel`, t.`maxlevel` = b.`maxlevel`;
DELETE FROM `basic_155k_level_backup`;

-- ---- 1. who counts as a monster ------------------------------------------------------
DROP TABLE IF EXISTS `tmp_155k_factions`;
CREATE TABLE `tmp_155k_factions` (`faction` int unsigned NOT NULL, `kind` char(1) NOT NULL, PRIMARY KEY (`faction`));
-- >>> GENERATED by scripts/generate-basic-outland-world-levels-sql — do not edit by hand
-- faction templates no player befriends (FactionTemplate.dbc): 307 hostile (h), 71 neutral (n)
INSERT INTO `tmp_155k_factions` (`faction`, `kind`) VALUES (14,'h'),(16,'h'),(17,'h'),(18,'h'),(19,'h'),(20,'h'),(21,'h'),(22,'h'),(24,'h'),(26,'h'),(27,'h'),(28,'h'),(30,'h'),(37,'h'),(38,'h'),(39,'h'),(40,'h'),(41,'h'),(44,'h'),(45,'h'),(46,'h'),(47,'h'),(48,'h'),(49,'h'),(50,'h'),(51,'h'),(54,'h'),(59,'h'),(60,'h'),(61,'h'),(62,'h'),(63,'h'),(66,'h'),(67,'h'),(70,'h'),(72,'h'),(73,'h'),(74,'h'),(78,'h'),(81,'h'),(82,'h'),(87,'h'),(89,'h'),(90,'h'),(91,'h'),(92,'h'),(93,'h'),(95,'h'),(97,'h'),(100,'h'),(101,'h'),(102,'h'),(103,'h'),(107,'h'),(108,'h'),(109,'h'),(110,'h'),(111,'h'),(112,'h'),(114,'h'),(119,'h'),(127,'h'),(128,'h'),(129,'h'),(130,'h'),(131,'h'),(134,'h'),(148,'h'),(152,'h'),(154,'h'),(168,'h'),(230,'h'),(233,'h'),(270,'h'),(310,'h'),(312,'h'),(370,'h'),(410,'h'),(411,'h'),(413,'h'),(414,'h'),(415,'h'),(450,'h'),(470,'h'),(472,'h'),(494,'h'),(514,'h'),(554,'h'),(574,'h'),(575,'h'),(636,'h'),(654,'h'),(655,'h'),(736,'h'),(754,'h'),(776,'h'),(778,'h'),(795,'h'),(834,'h'),(934,'h'),(954,'h'),(974,'h'),(1081,'h'),(1114,'h'),(1234,'h'),(1235,'h'),(1236,'h'),(1274,'h'),(1275,'h'),(1294,'h'),(1374,'h'),(1375,'h'),(1394,'h'),(1395,'h'),(1414,'h'),(1415,'h'),(1434,'h'),(1601,'h'),(1605,'h'),(1614,'h'),(1617,'h'),(1620,'h'),(1626,'h'),(1630,'h'),(1634,'h'),(1643,'h'),(1662,'h'),(1663,'h'),(1664,'h'),(1678,'h'),(1679,'h'),(1681,'h'),(1687,'h'),(1692,'h'),(1693,'h'),(1697,'h'),(1701,'h'),(1702,'h'),(1704,'h'),(1705,'h'),(1706,'h'),(1711,'h'),(1712,'h'),(1713,'h'),(1714,'h'),(1715,'h'),(1720,'h'),(1738,'h'),(1739,'h'),(1740,'h'),(1742,'h'),(1748,'h'),(1750,'h'),(1751,'h'),(1752,'h'),(1753,'h'),(1754,'h'),(1761,'h'),(1762,'h'),(1763,'h'),(1764,'h'),(1765,'h'),(1768,'h'),(1769,'h'),(1771,'h'),(1772,'h'),(1780,'h'),(1781,'h'),(1782,'h'),(1783,'h'),(1784,'h'),(1785,'h'),(1786,'h'),(1787,'h'),(1789,'h'),(1790,'h'),(1791,'h'),(1792,'h'),(1793,'h'),(1796,'h'),(1798,'h'),(1799,'h'),(1800,'h'),(1803,'h'),(1804,'h'),(1808,'h'),(1809,'h'),(1810,'h'),(1811,'h'),(1813,'h'),(1814,'h'),(1815,'h'),(1823,'h'),(1824,'h'),(1825,'h'),(1826,'h'),(1827,'h'),(1834,'h'),(1839,'h'),(1842,'h'),(1843,'h'),(1846,'h'),(1847,'h'),(1848,'h'),(1849,'h'),(1850,'h'),(1853,'h'),(1862,'h'),(1863,'h'),(1864,'h'),(1865,'h'),(1871,'h'),(1873,'h'),(1877,'h'),(1878,'h'),(1879,'h'),(1880,'h'),(1881,'h'),(1882,'h'),(1883,'h'),(1884,'h'),(1885,'h'),(1886,'h'),(1888,'h'),(1889,'h'),(1890,'h'),(1894,'h'),(1895,'h'),(1902,'h'),(1904,'h'),(1906,'h'),(1909,'h'),(1914,'h'),(1917,'h'),(1919,'h'),(1924,'h'),(1925,'h'),(1932,'h'),(1953,'h'),(1954,'h'),(1955,'h'),(1958,'h'),(1962,'h'),(1963,'h'),(1964,'h'),(1965,'h'),(1969,'h'),(1970,'h'),(1975,'h'),(1982,'h'),(1983,'h'),(1984,'h'),(1985,'h'),(1988,'h'),(1989,'h'),(1990,'h'),(1991,'h'),(1992,'h'),(1998,'h'),(2001,'h'),(2003,'h'),(2005,'h'),(2018,'h'),(2022,'h'),(2029,'h'),(2030,'h'),(2033,'h'),(2035,'h'),(2039,'h'),(2042,'h'),(2043,'h'),(2057,'h'),(2068,'h'),(2069,'h'),(2075,'h'),(2080,'h'),(2088,'h'),(2089,'h'),(2095,'h'),(2097,'h'),(2098,'h'),(2099,'h'),(2102,'h'),(2103,'h'),(2106,'h'),(2107,'h'),(2108,'h'),(2109,'h'),(2111,'h'),(2112,'h'),(2113,'h'),(2114,'h'),(2116,'h'),(2119,'h'),(2120,'h'),(2124,'h'),(2125,'h'),(2126,'h'),(2133,'h'),(2139,'h'),(2145,'h'),(2150,'h'),(2189,'h'),(2190,'h'),(2191,'h'),(2209,'h'),(2212,'h'),(7,'n'),(15,'n'),(25,'n'),(31,'n'),(32,'n'),(34,'n'),(36,'n'),(43,'n'),(52,'n'),(58,'n'),(77,'n'),(94,'n'),(99,'n'),(153,'n'),(188,'n'),(189,'n'),(190,'n'),(311,'n'),(330,'n'),(350,'n'),(416,'n'),(430,'n'),(594,'n'),(634,'n'),(674,'n'),(914,'n'),(1014,'n'),(1015,'n'),(1094,'n'),(1095,'n'),(1194,'n'),(1673,'n'),(1682,'n'),(1683,'n'),(1684,'n'),(1703,'n'),(1736,'n'),(1749,'n'),(1828,'n'),(1869,'n'),(1887,'n'),(1905,'n'),(1915,'n'),(1930,'n'),(1931,'n'),(1936,'n'),(1937,'n'),(1938,'n'),(1939,'n'),(1940,'n'),(1941,'n'),(1942,'n'),(1943,'n'),(1944,'n'),(1966,'n'),(1968,'n'),(1972,'n'),(1999,'n'),(2000,'n'),(2014,'n'),(2016,'n'),(2017,'n'),(2038,'n'),(2048,'n'),(2049,'n'),(2074,'n'),(2078,'n'),(2096,'n'),(2127,'n'),(2136,'n'),(2156,'n');
-- <<< GENERATED END

-- ---- 2. the raised templates and their step ----------------------------------------
DROP TABLE IF EXISTS `basic_155k_world_templates`;
CREATE TABLE `basic_155k_world_templates` (
  `entry`        int unsigned NOT NULL,
  `level_offset` tinyint      NOT NULL,
  PRIMARY KEY (`entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='issue 155k: raised Outland world templates and their step (read by scripts/validate-basic-state)';
INSERT INTO `basic_155k_world_templates` (`entry`, `level_offset`)
SELECT t.`entry`, IF(MIN(c.`position_x`) > 11350, 6, 4)
FROM `creature` c
JOIN `creature_template` t ON t.`entry` = c.`id`
JOIN `tmp_155k_factions` f ON f.`faction` = t.`faction`
WHERE t.`rank` <> 3 AND t.`type` <> 8 AND (t.`flags_extra` & 128) = 0
  AND IF(f.`kind` = 'n', t.`npcflag` = 0, (t.`npcflag` & ~3) = 0)     -- 1 gossip, 2 quest giver
  AND t.`entry` NOT IN (SELECT `entry` FROM `basic_155f_templates`)
GROUP BY t.`entry`
HAVING SUM(NOT (c.`map` = 530 AND (c.`position_y` > -2000 OR c.`position_x` > 11350))) = 0;

-- ---- 3. save, then raise -------------------------------------------------------------
INSERT INTO `basic_155k_level_backup` (`entry`, `minlevel`, `maxlevel`)
SELECT t.`entry`, t.`minlevel`, t.`maxlevel` FROM `creature_template` t JOIN `basic_155k_world_templates` w ON w.`entry` = t.`entry`;
UPDATE `creature_template` t JOIN `basic_155k_world_templates` w ON w.`entry` = t.`entry`
SET t.`minlevel` = t.`minlevel` + w.`level_offset`, t.`maxlevel` = t.`maxlevel` + w.`level_offset`;

DROP TABLE `tmp_155k_factions`;

-- ============================================================================
-- End of 17-outland-world-levels.sql (apply)
-- ============================================================================
