-- MARKER_E034_APPLY basic-titan-jewelers
-- ============================================================================
-- 19-titan-jewelers.sql (issue 155p, stage 2) — APPLY SOURCE
-- ============================================================================
-- At three places the titans shaped, a pair of Earthen (friendly to both
-- factions) stands side by side (Ritz, 2026-09-25):
--   * an Earthen Crystal-Keeper <Crystal Trader>: hand over a Nexus Crystal
--     (what disenchanting an Azeroth epic gives) for a random uncut Wrath
--     gem, uncommon, now and then rare. The trade itself is Lua
--     (src/lua-basic/titan-jewelers.lua);
--   * an Earthen Gemcutter <Masterwork Jewelcrafter>: a trainer, in the
--     stock trainer window, teaching for gold at Jewelcrafting 300 the Wrath
--     gem cuts stock taught only at trainers (the uncommon ones, and the
--     rare single-stat ones; no meta gems).
-- Where: outside Uldaman's front entrance (Badlands), beside the Uldum
-- Pedestal (Tanaris), and at one of Un'Goro's three Crystal Pylons. The
-- Un'Goro pair wanders: each pylon's pair is a game event (201 northern,
-- 202 western, 203 eastern) of the "internal" kind, which the server never
-- starts or stops on its own; the Lua script starts one at boot and every
-- 30 minutes, when no player is within 200 yards, swaps to one of the other
-- two at 50% each. Game events spawn and remove their creatures whether or
-- not anyone is nearby, which a script moving loaded creatures could not.
-- Spots, down to the ground's height: scripts/generate-basic-titan-jeweler-spots.
-- Ids this file owns: creatures 1550210 (trader) and 1550211 (gemcutter),
-- spawns 15501011–15501020, trainer list 155300, text 1553000, events
-- 201–203. Database: acore_world_basic. Applied by E034, after E033 (whose
-- gem-cut list, basic_155p_cuts, it reads) and E027 (whose saved trainer
-- rows give the cuts' stock prices).
-- ============================================================================

-- ---- 0. remove what an earlier apply made --------------------------------------------
DELETE FROM `game_event_creature`      WHERE `eventEntry` IN (201, 202, 203);
DELETE FROM `game_event`               WHERE `eventEntry` IN (201, 202, 203);
DELETE FROM `creature`                 WHERE `guid` BETWEEN 15501011 AND 15501020;
DELETE FROM `creature_default_trainer` WHERE `CreatureId` IN (1550210, 1550211);
DELETE FROM `trainer_spell`            WHERE `TrainerId` = 155300;
DELETE FROM `trainer`                  WHERE `Id` = 155300;
DELETE FROM `creature_template_model`  WHERE `CreatureID` IN (1550210, 1550211);
DELETE FROM `creature_template`        WHERE `entry` IN (1550210, 1550211);
DELETE FROM `npc_text`                 WHERE `ID` = 1553000;

-- ---- 1. the spots -----------------------------------------------------------------------
DROP TABLE IF EXISTS `tmp_155p_spots`;
CREATE TABLE `tmp_155p_spots` (
  `site` varchar(8) NOT NULL, `role` varchar(8) NOT NULL, `map` smallint unsigned NOT NULL,
  `x` float NOT NULL, `y` float NOT NULL, `z` float NOT NULL, `o` float NOT NULL, PRIMARY KEY (`site`, `role`));
-- >>> GENERATED by scripts/generate-basic-titan-jeweler-spots — do not edit by hand
-- site, role (trader = crystal trader, jeweler = masterwork jewelcrafter), map, x, y, ground z, facing
INSERT INTO `tmp_155p_spots` (`site`, `role`, `map`, `x`, `y`, `z`, `o`) VALUES ('pylon_e','jeweler',1,-7194.85,-2313.74,-238.61,4.398),('pylon_e','trader',1,-7198.65,-2312.50,-237.38,4.398),('pylon_n','jeweler',1,-6284.29,-1553.80,-231.56,6.035),('pylon_n','trader',1,-6285.28,-1557.68,-233.36,6.035),('pylon_w','jeweler',1,-7424.39,-358.58,-238.38,2.036),('pylon_w','trader',1,-7420.82,-356.79,-235.02,2.036),('uldaman','jeweler',0,-6072.84,-2954.01,209.78,0.063),('uldaman','trader',0,-6072.59,-2958.00,209.78,0.063),('uldum','jeweler',1,-9612.27,-2817.05,8.77,3.142),('uldum','trader',1,-9612.27,-2813.05,8.38,3.142);
-- <<< GENERATED END

-- ---- 2. the Earthen --------------------------------------------------------------------
-- copies of an Earthen Protector (28149, the trader) and an Earthen Dwarf
-- (27980, the gemcutter), made friendly to everyone (faction 35)
DROP TEMPORARY TABLE IF EXISTS `tmp_155p_template`;
CREATE TEMPORARY TABLE `tmp_155p_template` AS SELECT * FROM `creature_template` WHERE `entry` IN (28149, 27980);
UPDATE `tmp_155p_template` SET
  `name`    = IF(`entry` = 28149, 'Earthen Crystal-Keeper', 'Earthen Gemcutter'),
  `subname` = IF(`entry` = 28149, 'Crystal Trader', 'Masterwork Jewelcrafter'),
  `npcflag` = IF(`entry` = 28149, 1, 1 | 16 | 64),     -- gossip; gossip + trainer + profession trainer
  `entry`   = IF(`entry` = 28149, 1550210, 1550211),
  `difficulty_entry_1` = 0, `difficulty_entry_2` = 0, `difficulty_entry_3` = 0, `KillCredit1` = 0, `KillCredit2` = 0,
  `faction` = 35, `gossip_menu_id` = 0, `minlevel` = 60, `maxlevel` = 60,
  `lootid` = 0, `pickpocketloot` = 0, `skinloot` = 0, `AIName` = '', `ScriptName` = '';
INSERT INTO `creature_template` SELECT * FROM `tmp_155p_template`;
DROP TEMPORARY TABLE `tmp_155p_template`;
DROP TEMPORARY TABLE IF EXISTS `tmp_155p_model`;
CREATE TEMPORARY TABLE `tmp_155p_model` AS SELECT * FROM `creature_template_model` WHERE `CreatureID` IN (28149, 27980);
UPDATE `tmp_155p_model` SET `CreatureID` = IF(`CreatureID` = 28149, 1550210, 1550211);
INSERT INTO `creature_template_model` SELECT * FROM `tmp_155p_model`;
DROP TEMPORARY TABLE `tmp_155p_model`;

INSERT INTO `npc_text` (`ID`, `text0_0`, `text0_1`, `Probability0`) VALUES
  (1553000, 'The titans set crystals of power into everything they shaped. Bring me a Nexus Crystal and I will draw a gem out of it.',
            'The titans set crystals of power into everything they shaped. Bring me a Nexus Crystal and I will draw a gem out of it.', 1);

-- ---- 3. the gemcutter's list -----------------------------------------------------------
-- Wrath cuts that stock taught only at trainers: the uncommon ones (gems of
-- item level 70) and the rare single ones (80, not meta), from the stock
-- Grand Master list (111) that 155n's file saved; stock price, skill 300
INSERT INTO `trainer` (`Id`, `Type`, `Requirement`, `Greeting`, `VerifiedBuild`) VALUES
  (155300, 2, 0, 'The titans'' own cuts, for those at the height of the craft.', 0);
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (1550211, 155300);
INSERT IGNORE INTO `trainer_spell` (`TrainerId`, `SpellId`, `MoneyCost`, `ReqSkillLine`, `ReqSkillRank`, `ReqAbility1`, `ReqAbility2`, `ReqAbility3`, `ReqLevel`)
SELECT 155300, n.`SpellId`, n.`MoneyCost`, 755, 300, 0, 0, 0, 0
FROM `basic_155n_trainer_spell` n
JOIN `basic_155p_cuts` c ON c.`spell` = n.`SpellId`
JOIN `item_template` g ON g.`entry` = c.`item`
WHERE n.`TrainerId` = 111 AND g.`class` = 3 AND g.`GemProperties` <> 0 AND g.`subclass` <> 6
  AND ((g.`Quality` = 2 AND g.`ItemLevel` = 70) OR (g.`Quality` = 3 AND g.`ItemLevel` = 80));

-- ---- 4. spawns ---------------------------------------------------------------------------
-- 15501011–14: Uldaman and Uldum, always there; 15501015–20: the pylons'
-- pairs, each spawned only while its event runs
INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `Comment`)
SELECT 15501010 + CASE s.`site` WHEN 'uldaman' THEN 1 WHEN 'uldum' THEN 3 WHEN 'pylon_n' THEN 5 WHEN 'pylon_w' THEN 7 ELSE 9 END
                + IF(s.`role` = 'trader', 0, 1),
       IF(s.`role` = 'trader', 1550210, 1550211), s.`map`, 1, 1, s.`x`, s.`y`, s.`z`, s.`o`, 300,
       CONCAT('issue 155p: titan-site ', s.`role`, ', ', s.`site`)
FROM `tmp_155p_spots` s;
INSERT INTO `game_event` (`eventEntry`, `start_time`, `end_time`, `occurence`, `length`, `holiday`, `holidayStage`, `description`, `world_event`, `announce`) VALUES
  (201, '2000-01-01 00:00:00', '2000-01-01 00:00:00', 5184000, 2592000, 0, 0, 'basic 155p: titan jewelcrafters at the Northern Crystal Pylon', 5, 0),
  (202, '2000-01-01 00:00:00', '2000-01-01 00:00:00', 5184000, 2592000, 0, 0, 'basic 155p: titan jewelcrafters at the Western Crystal Pylon',  5, 0),
  (203, '2000-01-01 00:00:00', '2000-01-01 00:00:00', 5184000, 2592000, 0, 0, 'basic 155p: titan jewelcrafters at the Eastern Crystal Pylon',  5, 0);
INSERT INTO `game_event_creature` (`eventEntry`, `guid`) VALUES
  (201, 15501015), (201, 15501016),
  (202, 15501017), (202, 15501018),
  (203, 15501019), (203, 15501020);

DROP TABLE `tmp_155p_spots`;

-- ============================================================================
-- End of 19-titan-jewelers.sql (apply)
-- ============================================================================
