-- MARKER_E035_APPLY basic-sockets
-- ============================================================================
-- 20-sockets.sql (issue 155p, stage 3) — APPLY SOURCE
-- ============================================================================
-- Gem sockets on white gear sold in Azeroth's capitals and on blues from
-- vanilla's 5-person dungeons (design agreed with Ritz, 2026-09-25; quotes
-- in issue 155p):
--
--   gem tier    by item level: +4 gems below 30, +6 below 45, +8 from 45
--               (the smallest gems the client can describe; nothing below
--               item level 17 gets a socket, where a +4 gem outweighs a
--               green's whole stats)
--   whites      more sockets, small Stamina bonus: sockets and bonus sum
--               to about a same-level green's stats. At the capital sets'
--               item levels (17, 22, 27, 37, 50) the counts are the table
--               Ritz approved; elsewhere (weapons, shields) the same rule:
--               sockets = gems that fit the green's stats, bonus = the rest
--   blues       fewer sockets, big bonus of the item's own strongest stat:
--               fixed stats cut to about 80% of a same-level green's (an
--               empty-socket blue loses to the green), sockets and bonus
--               lift a filled one about 10% above its stock total; two
--               sockets only on chest, legs and two-handers with room for
--               both. Blues with random or no fixed stats keep stock form
--   colours     armor: red, yellow and blue as even as possible within each
--               white set (one armor type at one item level); a blue's
--               sockets take the gem colour of its two strongest stats
--               (red: Strength, Agility, attack and spell power; yellow:
--               Intellect and ratings; blue: Stamina, Spirit, resilience,
--               mana every 5 seconds). Weapons: colourless (prismatic)
--               sockets, no bonus
--   honesty     bonuses are enchantments whose whole effect is one stat
--               and whose text says exactly that (generated list)
--
-- "A same-level green's stats": the average total of fixed-stat greens in
-- the item's 5-level band and slot size (big: chest, legs, two-handers;
-- middle: head, shoulders, hands, feet, waist, one-handers, off-hands;
-- small: wrist, neck, rings, back, ranged).
-- Items that already have sockets are left alone. Every changed column is
-- saved (basic_155p_socket_backup); each apply first restores them.
-- Database: acore_world_basic. Applied by E035. Durability of white gear
-- is a separate patch.
-- ============================================================================

-- ---- 0. put back what an earlier apply changed -----------------------------------------
CREATE TABLE IF NOT EXISTS `basic_155p_socket_backup` (PRIMARY KEY (`entry`))
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='issue 155p: stock sockets and stats of every item stage 3 socketed, for the revert'
SELECT `entry`, `socketColor_1`, `socketColor_2`, `socketColor_3`, `socketBonus`,
       `stat_value1`, `stat_value2`, `stat_value3`, `stat_value4`, `stat_value5`,
       `stat_value6`, `stat_value7`, `stat_value8`, `stat_value9`, `stat_value10`
FROM `item_template` LIMIT 0;
UPDATE `item_template` i JOIN `basic_155p_socket_backup` b ON b.`entry` = i.`entry` SET
  i.`socketColor_1` = b.`socketColor_1`, i.`socketColor_2` = b.`socketColor_2`, i.`socketColor_3` = b.`socketColor_3`,
  i.`socketBonus` = b.`socketBonus`,
  i.`stat_value1` = b.`stat_value1`, i.`stat_value2` = b.`stat_value2`, i.`stat_value3` = b.`stat_value3`,
  i.`stat_value4` = b.`stat_value4`, i.`stat_value5` = b.`stat_value5`, i.`stat_value6` = b.`stat_value6`,
  i.`stat_value7` = b.`stat_value7`, i.`stat_value8` = b.`stat_value8`, i.`stat_value9` = b.`stat_value9`,
  i.`stat_value10` = b.`stat_value10`;
DELETE FROM `basic_155p_socket_backup`;

-- ---- 1. generated lists -------------------------------------------------------------------
DROP TABLE IF EXISTS `tmp_155p_bonus`;
CREATE TABLE `tmp_155p_bonus` (`enchant` int unsigned NOT NULL, `stat` tinyint unsigned NOT NULL, `amount` smallint unsigned NOT NULL, PRIMARY KEY (`enchant`));
DROP TABLE IF EXISTS `tmp_155p_dungeons`;
CREATE TABLE `tmp_155p_dungeons` (`map_id` smallint unsigned NOT NULL, PRIMARY KEY (`map_id`));
DROP TABLE IF EXISTS `tmp_155p_capitals`;
CREATE TABLE `tmp_155p_capitals` (`area` int unsigned NOT NULL, `side` tinyint unsigned NOT NULL, `map` smallint unsigned NOT NULL,
  `x0` float NOT NULL, `x1` float NOT NULL, `y0` float NOT NULL, `y1` float NOT NULL, PRIMARY KEY (`area`));
-- >>> GENERATED by scripts/generate-basic-sockets-sql — do not edit by hand
-- honest one-stat enchantments (SpellItemEnchantment.dbc): enchantment, stat, amount: 864
INSERT INTO `tmp_155p_bonus` (`enchant`, `stat`, `amount`) VALUES (38,12,5),(64,6,3),(66,7,1),(68,4,1),(69,4,2),(70,4,3),(71,7,1),(72,7,2),(73,7,3),(74,3,1),(75,3,2),(76,3,3),(79,5,1),(80,5,2),(81,5,3),(82,6,1),(83,6,2),(84,6,3),(90,3,4),(91,3,5),(92,3,6),(93,3,7),(94,5,4),(95,5,5),(96,5,6),(97,5,7),(98,6,4),(99,6,5),(100,6,6),(101,6,7),(102,7,4),(103,7,5),(104,7,6),(105,7,7),(106,4,4),(107,4,5),(108,4,6),(109,4,7),(110,12,1),(111,12,2),(112,12,3),(113,12,4),(114,12,5),(115,12,6),(116,12,7),(195,32,14),(196,32,28),(197,32,42),(198,32,56),(206,45,1),(207,45,2),(208,45,4),(209,45,5),(211,45,7),(212,45,8),(243,6,1),(244,5,4),(247,3,1),(248,4,1),(251,5,1),(252,6,6),(255,6,3),(343,3,8),(349,3,9),(350,5,8),(351,6,8),(352,4,8),(353,7,8),(354,5,9),(355,6,9),(356,7,9),(357,4,9),(358,3,10),(359,5,10),(360,6,10),(361,7,10),(362,4,10),(363,3,11),(364,5,11),(365,6,11),(366,7,11),(367,4,11),(368,3,12),(369,5,12),(370,6,12),(371,7,12),(372,4,12),(403,3,13),(404,3,14),(405,5,13),(406,5,14),(407,6,13),(408,6,14),(409,7,13),(410,4,13),(411,7,14),(412,4,14),(423,45,1),(424,45,2),(426,45,5),(428,45,7),(429,45,8),(430,45,9),(431,45,11),(432,45,12),(436,32,70),(440,45,9),(441,45,11),(442,45,12),(684,4,15),(723,5,3),(724,7,3),(823,4,3),(849,3,3),(851,6,5),(852,7,5),(856,4,5),(883,3,15),(904,3,5),(905,5,5),(907,6,7),(923,12,5),(924,12,2),(925,12,3),(927,4,7),(929,7,7),(931,36,10),(983,3,16),(1043,4,16),(1044,4,17),(1045,4,18),(1046,4,19),(1047,4,20),(1048,4,21),(1049,4,22),(1050,4,23),(1051,4,24),(1052,4,25),(1053,4,26),(1054,4,27),(1055,4,28),(1056,4,29),(1057,4,30),(1058,4,31),(1059,4,32),(1060,4,33),(1061,4,34),(1062,4,35),(1063,4,36),(1064,4,37),(1065,4,38),(1066,4,39),(1067,4,40),(1068,7,15),(1069,7,16),(1070,7,17),(1071,7,18),(1072,7,19),(1073,7,20),(1074,7,21),(1075,7,22),(1076,7,23),(1077,7,24),(1078,7,25),(1079,7,26),(1080,7,27),(1081,7,28),(1082,7,29),(1083,7,30),(1084,7,31),(1085,7,32),(1086,7,33),(1087,7,34),(1088,7,35),(1089,7,36),(1090,7,37),(1091,7,38),(1092,7,39),(1093,7,40),(1094,3,17),(1095,3,18),(1096,3,19),(1097,3,20),(1098,3,21),(1099,3,22),(1100,3,23),(1101,3,24),(1102,3,25),(1103,3,26),(1104,3,27),(1105,3,28),(1106,3,29),(1107,3,30),(1108,3,31),(1109,3,32),(1110,3,33),(1111,3,34),(1112,3,35),(1113,3,36),(1114,3,37),(1115,3,38),(1116,3,39),(1117,3,40),(1118,5,15),(1119,5,16),(1120,5,17),(1121,5,18),(1122,5,19),(1123,5,20),(1124,5,21),(1125,5,22),(1126,5,23),(1127,5,24),(1128,5,25),(1129,5,26),(1130,5,27),(1131,5,28),(1132,5,29),(1133,5,30),(1134,5,31),(1135,5,32),(1136,5,33),(1137,5,34),(1138,5,35),(1139,5,36),(1140,5,37),(1141,5,38),(1142,5,39),(1143,5,40),(1144,6,15),(1145,6,16),(1146,6,17),(1147,6,18),(1148,6,19),(1149,6,20),(1150,6,21),(1151,6,22),(1152,6,23),(1153,6,24),(1154,6,25),(1155,6,26),(1156,6,27),(1157,6,28),(1158,6,29),(1159,6,30),(1160,6,31),(1161,6,32),(1162,6,33),(1163,6,34),(1164,6,36),(1165,6,37),(1166,6,38),(1167,6,39),(1168,6,40),(1183,6,35),(1203,4,41),(1204,4,42),(1205,4,43),(1206,4,44),(1207,4,45),(1208,4,46),(1209,7,41),(1210,7,42),(1211,7,43),(1212,7,44),(1213,7,45),(1214,7,46),(1215,3,41),(1216,3,42),(1217,3,43),(1218,3,44),(1219,3,45),(1220,3,46),(1221,5,41),(1222,5,42),(1223,5,43),(1224,5,44),(1225,5,45),(1226,5,46),(1227,6,41),(1228,6,42),(1229,6,43),(1230,6,44),(1231,6,45),(1232,6,46),(1506,4,8),(1507,7,8),(1508,3,8),(1509,5,8),(1510,6,8),(1563,38,2),(1583,38,4),(1584,38,6),(1585,38,8),(1586,38,10),(1587,38,12),(1588,38,14),(1589,38,16),(1590,38,18),(1591,38,20),(1592,38,22),(1593,38,24),(1594,38,26),(1595,38,28),(1596,38,30),(1597,38,32),(1598,38,34),(1599,38,36),(1600,38,38),(1601,38,32),(1602,38,42),(1603,38,44),(1604,38,46),(1605,38,48),(1606,38,50),(1607,38,52),(1608,38,54),(1609,38,56),(1610,38,58),(1611,38,60),(1612,38,62),(1613,38,64),(1614,38,66),(1615,38,68),(1616,38,70),(1617,38,72),(1618,38,74),(1619,38,76),(1620,38,78),(1621,38,80),(1622,38,82),(1623,38,84),(1624,38,86),(1625,38,88),(1626,38,90),(1627,38,92),(1883,5,7),(1884,6,9),(1885,4,9),(1886,7,9),(1887,3,7),(1901,5,9),(1903,6,9),(1904,5,9),(1943,12,12),(1944,12,8),(1945,12,9),(1946,12,10),(1947,12,11),(1948,12,13),(1949,12,14),(1950,12,15),(1951,12,16),(1952,12,20),(1953,12,22),(1954,12,25),(1955,12,32),(1956,12,17),(1957,12,18),(1958,12,19),(1959,12,21),(1960,12,23),(1961,12,24),(1962,12,26),(1963,12,27),(1964,12,28),(1965,12,29),(1966,12,30),(1967,12,31),(1968,12,33),(1969,12,34),(1970,12,35),(1971,12,36),(1972,12,37),(1973,12,38),(1983,15,5),(1984,15,10),(1985,15,15),(1986,15,20),(2078,13,12),(2307,45,1),(2308,45,2),(2309,45,4),(2310,45,5),(2312,45,7),(2313,45,8),(2314,45,9),(2315,45,11),(2316,45,12),(2317,45,13),(2318,45,14),(2319,45,15),(2320,45,16),(2321,45,18),(2322,45,19),(2323,45,20),(2324,45,21),(2325,45,22),(2326,45,23),(2327,45,25),(2328,45,26),(2329,45,27),(2330,45,28),(2331,45,29),(2332,45,30),(2333,45,32),(2334,45,33),(2335,45,34),(2336,45,35),(2337,45,36),(2338,45,37),(2339,45,39),(2340,45,40),(2341,45,41),(2342,45,42),(2343,45,43),(2344,45,44),(2503,12,5),(2504,45,30),(2505,45,29),(2543,36,10),(2544,45,8),(2545,13,12),(2563,4,15),(2564,3,15),(2566,45,13),(2567,6,20),(2568,5,22),(2604,45,18),(2605,45,18),(2606,38,30),(2607,45,12),(2608,45,13),(2609,45,15),(2610,45,14),(2612,45,18),(2617,45,16),(2618,3,15),(2622,13,12),(2646,3,25),(2647,4,12),(2648,12,12),(2649,7,12),(2650,45,15),(2651,45,12),(2652,45,11),(2654,5,12),(2657,3,12),(2665,6,35),(2666,5,30),(2667,38,70),(2668,4,20),(2669,45,40),(2670,3,35),(2686,4,8),(2687,3,8),(2688,7,8),(2690,45,7),(2691,4,6),(2692,45,7),(2693,3,6),(2694,5,6),(2695,32,6),(2696,12,6),(2697,31,6),(2698,7,9),(2699,6,6),(2701,43,3),(2725,4,8),(2726,3,8),(2727,45,9),(2728,45,9),(2729,38,16),(2730,13,8),(2731,7,12),(2732,6,8),(2733,43,4),(2734,5,8),(2735,32,8),(2736,32,8),(2737,12,8),(2749,5,12),(2751,32,14),(2754,14,8),(2759,35,8),(2764,31,8),(2766,5,8),(2767,31,8),(2768,45,16),(2769,31,11),(2770,45,7),(2771,32,8),(2772,32,14),(2773,32,16),(2774,5,11),(2775,32,11),(2776,43,3),(2777,6,13),(2779,6,16),(2781,7,19),(2782,3,10),(2783,31,14),(2784,31,12),(2785,31,13),(2786,31,7),(2787,32,8),(2792,7,8),(2793,12,8),(2796,13,15),(2797,13,9),(2837,6,7),(2838,32,7),(2839,32,14),(2840,7,21),(2841,7,10),(2842,6,8),(2843,32,8),(2844,31,8),(2845,31,11),(2850,32,13),(2851,7,19),(2856,35,4),(2859,35,3),(2860,31,3),(2861,12,3),(2862,35,3),(2863,5,3),(2864,32,4),(2866,6,3),(2867,35,2),(2868,7,6),(2869,5,4),(2870,14,3),(2871,13,4),(2872,45,5),(2873,31,4),(2874,32,4),(2875,32,3),(2876,13,3),(2877,3,4),(2878,35,4),(2879,4,3),(2880,31,3),(2882,7,6),(2883,7,4),(2884,32,2),(2885,32,2),(2886,31,2),(2887,32,3),(2889,45,5),(2890,6,4),(2891,35,10),(2892,4,4),(2893,3,3),(2894,4,7),(2895,7,4),(2896,45,8),(2900,45,4),(2901,45,2),(2902,32,2),(2907,14,2),(2908,31,4),(2909,31,2),(2910,45,3),(2911,4,10),(2912,45,12),(2913,32,10),(2914,32,10),(2919,4,7),(2922,4,7),(2924,45,8),(2925,7,3),(2926,13,2),(2927,4,4),(2928,45,12),(2930,45,12),(2932,12,4),(2933,35,15),(2934,32,10),(2935,31,15),(2936,38,8),(2937,45,20),(2941,31,2),(2942,32,6),(2943,38,14),(2944,38,14),(2945,38,20),(2949,38,20),(2950,32,10),(2951,32,4),(2952,32,4),(2953,45,2),(2956,4,4),(2957,3,4),(2958,45,5),(2959,45,5),(2960,38,8),(2961,7,6),(2962,6,4),(2963,43,2),(2964,5,4),(2965,32,4),(2966,31,4),(2967,32,4),(2968,12,4),(2971,38,12),(2972,15,4),(2973,38,6),(2974,45,4),(2976,12,2),(2977,13,13),(2979,45,15),(2981,45,15),(2983,38,26),(2990,12,13),(2994,32,13),(2996,32,13),(3015,4,2),(3016,5,2),(3017,15,3),(3065,4,8),(3092,32,3),(3094,37,4),(3097,6,2),(3098,45,2),(3103,4,8),(3104,31,6),(3105,31,8),(3114,38,4),(3115,4,10),(3116,3,10),(3117,45,12),(3118,45,12),(3119,38,20),(3120,13,10),(3121,14,10),(3122,7,15),(3123,6,10),(3124,43,5),(3126,5,10),(3127,32,10),(3128,31,10),(3129,32,10),(3130,12,10),(3131,35,10),(3132,31,10),(3149,3,2),(3151,45,2),(3152,32,2),(3153,45,2),(3164,7,3),(3197,38,20),(3198,45,5),(3204,32,3),(3205,32,3),(3206,3,8),(3207,4,12),(3208,38,24),(3209,3,12),(3210,45,14),(3211,45,14),(3212,7,18),(3213,43,6),(3214,6,12),(3215,35,12),(3216,5,12),(3217,32,12),(3218,31,12),(3219,31,12),(3220,32,12),(3221,12,12),(3222,3,20),(3224,3,6),(3227,32,10),(3228,38,34),(3229,35,12),(3231,37,15),(3234,31,20),(3240,45,23),(3245,35,20),(3246,45,28),(3248,37,18),(3249,32,16),(3255,45,55),(3257,45,54),(3258,45,18),(3259,7,22),(3262,7,15),(3263,32,4),(3267,36,4),(3268,7,15),(3270,36,8),(3276,38,20),(3277,45,12),(3278,45,12),(3279,45,3),(3281,38,20),(3282,45,12),(3283,45,12),(3287,36,10),(3292,38,68),(3293,7,51),(3295,36,16),(3300,45,19),(3301,32,6),(3302,12,8),(3303,36,8),(3304,13,8),(3305,7,12),(3307,7,9),(3308,36,4),(3309,36,6),(3310,5,6),(3311,6,6),(3312,4,8),(3313,3,8),(3314,32,8),(3316,32,6),(3317,7,21),(3324,32,10),(3329,7,12),(3330,7,18),(3335,38,20),(3336,32,10),(3339,45,12),(3340,32,10),(3351,31,6),(3352,6,8),(3353,5,8),(3354,7,12),(3355,3,6),(3356,38,12),(3357,4,6),(3358,13,6),(3359,14,4),(3360,14,8),(3361,15,6),(3362,37,6),(3371,4,12),(3374,3,12),(3375,38,24),(3376,13,12),(3377,14,12),(3379,37,12),(3380,45,14),(3381,5,12),(3382,32,12),(3383,31,12),(3384,12,12),(3385,35,12),(3386,36,12),(3387,7,18),(3388,6,12),(3389,43,6),(3446,4,16),(3447,3,16),(3448,45,19),(3449,38,32),(3450,13,16),(3451,14,16),(3453,37,16),(3454,7,24),(3455,6,16),(3456,43,8),(3458,5,16),(3459,32,16),(3460,31,16),(3461,12,16),(3462,35,16),(3463,36,16),(3518,4,20),(3519,3,20),(3520,45,23),(3521,38,40),(3522,13,20),(3523,14,20),(3524,37,20),(3526,5,20),(3527,32,20),(3528,31,20),(3529,12,20),(3530,35,20),(3531,36,20),(3532,7,30),(3533,6,20),(3534,43,10),(3596,45,5),(3600,35,6),(3602,45,7),(3644,3,14),(3646,13,14),(3647,37,14),(3648,14,14),(3649,4,14),(3650,45,16),(3651,38,28),(3653,6,14),(3654,43,7),(3655,7,21),(3657,32,14),(3658,12,14),(3659,36,14),(3660,31,14),(3661,5,14),(3662,35,14),(3732,4,34),(3733,3,34),(3734,45,39),(3735,6,34),(3736,43,17),(3737,5,34),(3738,32,34),(3739,36,34),(3740,13,34),(3741,14,34),(3742,31,34),(3743,12,34),(3744,35,34),(3746,37,34),(3751,12,6),(3752,45,5),(3753,45,9),(3756,38,130),(3757,7,102),(3758,45,76),(3764,38,12),(3766,7,12),(3778,37,8),(3791,7,30),(3792,35,20),(3821,35,8),(3824,38,24),(3825,36,15),(3827,38,110),(3828,38,85),(3829,38,35),(3830,45,50),(3831,36,23),(3833,38,65),(3834,45,63),(3839,38,40),(3840,45,23),(3841,45,23),(3844,6,45),(3845,38,50),(3846,45,40),(3850,7,40),(3851,7,50),(3854,45,81),(3855,45,69),(3856,3,100),(3857,12,6),(3858,31,5),(3861,4,20),(3862,3,20),(3863,7,30),(3864,6,20),(3865,5,20),(3866,45,23),(3867,31,20),(3871,14,6),(3874,38,130),(3877,38,16),(3881,43,17);
-- vanilla 5-person dungeons (Map.dbc): Shadowfang Keep, Stormwind Stockade, Deadmines, Wailing Caverns, <unused> Monastery, Razorfen Kraul, Blackfathom Deeps, Uldaman, Gnomeregan, Sunken Temple, Razorfen Downs, Scarlet Monastery, Zul'Farrak, Blackrock Spire, Blackrock Depths, Scholomance, Stratholme, Maraudon, Ragefire Chasm, Dire Maul
INSERT INTO `tmp_155p_dungeons` (`map_id`) VALUES (33),(34),(36),(43),(44),(47),(48),(70),(90),(109),(129),(189),(209),(229),(230),(289),(329),(349),(389),(429);
-- Azeroth's capitals: area, side, map, x and y bounds (WorldMapArea.dbc)
INSERT INTO `tmp_155p_capitals` (`area`, `side`, `map`, `x0`, `x1`, `y0`, `y1`) VALUES (1519,1,0,-9154,-7996,-15,1723),(1637,2,1,1338,2274,-5083,-3681),(1537,1,0,-5097,-4569,-1504,-714),(1638,2,1,-1546,-850,-527,517),(1657,1,1,9533,10238,1880,2938),(1497,2,0,1238,1878,-86,873);
-- <<< GENERATED END

-- ---- 2. what a green carries ----------------------------------------------------------------
-- slot size by inventory type: 1 big, 2 middle, 3 small (others get no sockets)
DROP TABLE IF EXISTS `tmp_155p_slot`;
CREATE TABLE `tmp_155p_slot` (`inv` tinyint unsigned NOT NULL, `size` tinyint unsigned NOT NULL, PRIMARY KEY (`inv`));
INSERT INTO `tmp_155p_slot` VALUES
  (5,1),(20,1),(7,1),(17,1),                                   -- chest, robe, legs, two-hander
  (1,2),(3,2),(10,2),(8,2),(6,2),(13,2),(21,2),(22,2),(14,2),(23,2),   -- head, shoulders, hands, feet, waist, one-handers, off-hand, shield, held
  (9,3),(2,3),(11,3),(16,3),(15,3),(25,3),(26,3),(28,3);      -- wrist, neck, finger, back, ranged, thrown, ranged right, relic
DROP TABLE IF EXISTS `tmp_155p_green`;
CREATE TABLE `tmp_155p_green` (`band` smallint unsigned NOT NULL, `size` tinyint unsigned NOT NULL, `g` float NOT NULL, PRIMARY KEY (`band`, `size`));
INSERT INTO `tmp_155p_green`
SELECT FLOOR(i.`ItemLevel` / 5) * 5, s.`size`,
       AVG(i.`stat_value1` + i.`stat_value2` + i.`stat_value3` + i.`stat_value4` + i.`stat_value5`
         + i.`stat_value6` + i.`stat_value7` + i.`stat_value8` + i.`stat_value9` + i.`stat_value10`)
FROM `item_template` i JOIN `tmp_155p_slot` s ON s.`inv` = i.`InventoryType`
WHERE i.`Quality` = 2 AND i.`class` IN (2, 4) AND i.`RandomProperty` = 0 AND i.`RandomSuffix` = 0
  AND i.`ItemLevel` BETWEEN 15 AND 69
  AND (i.`stat_value1` + i.`stat_value2` + i.`stat_value3` + i.`stat_value4` + i.`stat_value5`
     + i.`stat_value6` + i.`stat_value7` + i.`stat_value8` + i.`stat_value9` + i.`stat_value10`) > 0
GROUP BY FLOOR(i.`ItemLevel` / 5) * 5, s.`size`;

-- ---- 3. which items --------------------------------------------------------------------------
DROP TABLE IF EXISTS `tmp_155p_items`;
CREATE TABLE `tmp_155p_items` (
  `entry` int unsigned NOT NULL, `kind` char(1) NOT NULL COMMENT 'w white, b blue',
  `weapon` tinyint unsigned NOT NULL, `size` tinyint unsigned NOT NULL, `lvl` smallint unsigned NOT NULL,
  `setkey` varchar(24) NOT NULL, `inv` tinyint unsigned NOT NULL,
  `gem` tinyint unsigned NOT NULL, `g` float NOT NULL, `total` int NOT NULL DEFAULT 0,
  `sockets` tinyint unsigned NOT NULL DEFAULT 0, `bonus` smallint unsigned NOT NULL DEFAULT 0,
  `keep` float NOT NULL DEFAULT 1, `top1` tinyint unsigned NOT NULL DEFAULT 0, `top2` tinyint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`entry`));
-- whites sold by vendors standing in the capitals (not fishing poles,
-- miscellaneous or thrown weapons)
INSERT IGNORE INTO `tmp_155p_items` (`entry`, `kind`, `weapon`, `size`, `lvl`, `setkey`, `inv`, `gem`, `g`)
SELECT DISTINCT i.`entry`, 'w', i.`class` = 2, s.`size`, i.`ItemLevel`, CONCAT(i.`class`, '-', i.`subclass`, '-', i.`ItemLevel`), i.`InventoryType`,
       IF(i.`ItemLevel` < 30, 4, IF(i.`ItemLevel` < 45, 6, 8)), gr.`g`
FROM `tmp_155p_capitals` k
JOIN `creature` c ON c.`map` = k.`map` AND c.`position_x` BETWEEN k.`x0` AND k.`x1` AND c.`position_y` BETWEEN k.`y0` AND k.`y1`
JOIN `npc_vendor` v ON v.`entry` = c.`id`
JOIN `item_template` i ON i.`entry` = v.`item`
JOIN `tmp_155p_slot` s ON s.`inv` = i.`InventoryType`
JOIN `tmp_155p_green` gr ON gr.`band` = FLOOR(i.`ItemLevel` / 5) * 5 AND gr.`size` = s.`size`
WHERE i.`Quality` = 1 AND i.`class` IN (2, 4) AND i.`ItemLevel` BETWEEN 17 AND 63
  AND NOT (i.`class` = 2 AND i.`subclass` IN (14, 16, 20))
  AND i.`socketColor_1` = 0 AND i.`socketColor_2` = 0 AND i.`socketColor_3` = 0;

-- blues from vanilla's 5-person dungeons: their creatures' and chests' loot,
-- references followed three levels deep
DROP TABLE IF EXISTS `tmp_155p_src`;
CREATE TABLE `tmp_155p_src` (`kind` char(1) NOT NULL, `id` int unsigned NOT NULL, PRIMARY KEY (`kind`, `id`));
INSERT IGNORE INTO `tmp_155p_src` SELECT 'c', t.`lootid` FROM `creature` c JOIN `creature_template` t ON t.`entry` = c.`id`
WHERE c.`map` IN (SELECT `map_id` FROM `tmp_155p_dungeons`) AND t.`lootid` <> 0;
INSERT IGNORE INTO `tmp_155p_src` SELECT 'g', g.`Data1` FROM `gameobject` o JOIN `gameobject_template` g ON g.`entry` = o.`id`
WHERE o.`map` IN (SELECT `map_id` FROM `tmp_155p_dungeons`) AND g.`type` = 3 AND g.`Data1` <> 0;
INSERT IGNORE INTO `tmp_155p_src` SELECT 'r', l.`Reference` FROM `creature_loot_template` l JOIN `tmp_155p_src` k ON k.`kind` = 'c' AND k.`id` = l.`Entry` WHERE l.`Reference` <> 0;
INSERT IGNORE INTO `tmp_155p_src` SELECT 'r', l.`Reference` FROM `gameobject_loot_template` l JOIN `tmp_155p_src` k ON k.`kind` = 'g' AND k.`id` = l.`Entry` WHERE l.`Reference` <> 0;
DROP TABLE IF EXISTS `tmp_155p_step`;
CREATE TABLE `tmp_155p_step` (`id` int unsigned NOT NULL, PRIMARY KEY (`id`));
INSERT IGNORE INTO `tmp_155p_step` SELECT l.`Reference` FROM `reference_loot_template` l JOIN `tmp_155p_src` k ON k.`kind` = 'r' AND k.`id` = l.`Entry` WHERE l.`Reference` <> 0;
INSERT IGNORE INTO `tmp_155p_src` SELECT 'r', `id` FROM `tmp_155p_step`;
DELETE FROM `tmp_155p_step`;
INSERT IGNORE INTO `tmp_155p_step` SELECT l.`Reference` FROM `reference_loot_template` l JOIN `tmp_155p_src` k ON k.`kind` = 'r' AND k.`id` = l.`Entry` WHERE l.`Reference` <> 0;
INSERT IGNORE INTO `tmp_155p_src` SELECT 'r', `id` FROM `tmp_155p_step`;
DROP TABLE IF EXISTS `tmp_155p_loot`;
CREATE TABLE `tmp_155p_loot` (`item` int unsigned NOT NULL, PRIMARY KEY (`item`));
INSERT IGNORE INTO `tmp_155p_loot` SELECT l.`Item` FROM `creature_loot_template` l   JOIN `tmp_155p_src` k ON k.`kind` = 'c' AND k.`id` = l.`Entry` WHERE l.`Reference` = 0;
INSERT IGNORE INTO `tmp_155p_loot` SELECT l.`Item` FROM `gameobject_loot_template` l JOIN `tmp_155p_src` k ON k.`kind` = 'g' AND k.`id` = l.`Entry` WHERE l.`Reference` = 0;
INSERT IGNORE INTO `tmp_155p_loot` SELECT l.`Item` FROM `reference_loot_template` l  JOIN `tmp_155p_src` k ON k.`kind` = 'r' AND k.`id` = l.`Entry` WHERE l.`Reference` = 0;

INSERT IGNORE INTO `tmp_155p_items` (`entry`, `kind`, `weapon`, `size`, `lvl`, `setkey`, `inv`, `gem`, `g`, `total`)
SELECT i.`entry`, 'b', i.`class` = 2, s.`size`, i.`ItemLevel`, CONCAT('blue-', i.`entry`), i.`InventoryType`,
       IF(i.`ItemLevel` < 30, 4, IF(i.`ItemLevel` < 45, 6, 8)), gr.`g`,
       GREATEST(i.`stat_value1`, 0) + GREATEST(i.`stat_value2`, 0) + GREATEST(i.`stat_value3`, 0) + GREATEST(i.`stat_value4`, 0)
     + GREATEST(i.`stat_value5`, 0) + GREATEST(i.`stat_value6`, 0) + GREATEST(i.`stat_value7`, 0) + GREATEST(i.`stat_value8`, 0)
     + GREATEST(i.`stat_value9`, 0) + GREATEST(i.`stat_value10`, 0)
FROM `tmp_155p_loot` l
JOIN `item_template` i ON i.`entry` = l.`item`
JOIN `tmp_155p_slot` s ON s.`inv` = i.`InventoryType`
JOIN `tmp_155p_green` gr ON gr.`band` = FLOOR(i.`ItemLevel` / 5) * 5 AND gr.`size` = s.`size`
WHERE i.`Quality` = 3 AND i.`class` IN (2, 4) AND i.`ItemLevel` BETWEEN 17 AND 63
  AND i.`RandomProperty` = 0 AND i.`RandomSuffix` = 0
  AND i.`socketColor_1` = 0 AND i.`socketColor_2` = 0 AND i.`socketColor_3` = 0;
DELETE FROM `tmp_155p_items` WHERE `kind` = 'b' AND `total` <= 0;     -- nothing to drain

-- ---- 4. sockets, bonus, and what the blues keep ----------------------------------------------
-- whites: Ritz's approved table at the capital sets' item levels, the same
-- rule elsewhere; weapons fill with gems only
DROP TABLE IF EXISTS `tmp_155p_table`;
CREATE TABLE `tmp_155p_table` (`lvl` smallint unsigned NOT NULL, `size` tinyint unsigned NOT NULL, `sockets` tinyint unsigned NOT NULL, `bonus` tinyint unsigned NOT NULL, PRIMARY KEY (`lvl`, `size`));
INSERT INTO `tmp_155p_table` VALUES
  (17,1,1,2),(17,2,1,1),(17,3,1,0),
  (22,1,2,1),(22,2,1,3),(22,3,1,1),
  (27,1,3,0),(27,2,2,2),(27,3,1,2),
  (37,1,3,0),(37,2,2,3),(37,3,1,4),
  (50,1,3,2),(50,2,2,5),(50,3,2,0);
UPDATE `tmp_155p_items` t LEFT JOIN `tmp_155p_table` a ON a.`lvl` = t.`lvl` AND a.`size` = t.`size` SET
  t.`sockets` = IF(t.`weapon`, LEAST(3, GREATEST(1, ROUND(t.`g` / t.`gem`))),
                  COALESCE(a.`sockets`, LEAST(3, GREATEST(1, FLOOR(t.`g` / t.`gem` + 0.25))))),
  t.`bonus`   = IF(t.`weapon`, 0, COALESCE(a.`bonus`, GREATEST(0, ROUND(t.`g` - GREATEST(1, FLOOR(t.`g` / t.`gem` + 0.25)) * t.`gem`))))
WHERE t.`kind` = 'w';
-- blues: keep = the share of fixed stats left (80% of a green, never more
-- than stock); room = what gems and bonus make up, to 110% of stock
UPDATE `tmp_155p_items` SET `keep` = LEAST(1, 0.8 * `g` / `total`) WHERE `kind` = 'b';
UPDATE `tmp_155p_items` SET
  `sockets` = IF(`weapon`, LEAST(3, GREATEST(1, ROUND((1.1 * `total` - `keep` * `total`) / `gem`))),
                 1 + IF(`size` = 1 AND (1.1 * `total` - `keep` * `total`) >= 2.5 * `gem`, 1, 0)),
  `bonus`   = 0
WHERE `kind` = 'b';
UPDATE `tmp_155p_items` SET `bonus` = GREATEST(0, ROUND(1.1 * `total` - `keep` * `total` - `sockets` * `gem`))
WHERE `kind` = 'b' AND NOT `weapon`;
-- a blue with too little room for even one gem keeps its stock form
DELETE FROM `tmp_155p_items` WHERE `kind` = 'b' AND (1.1 * `total` - `keep` * `total`) < 0.75 * `gem`;

-- the blues' two strongest stats (by value), for colours and the bonus stat
DROP TABLE IF EXISTS `tmp_155p_stats`;
CREATE TABLE `tmp_155p_stats` (`entry` int unsigned NOT NULL, `stat` tinyint unsigned NOT NULL, `val` int NOT NULL, KEY (`entry`));
INSERT INTO `tmp_155p_stats`
SELECT i.`entry`, x.`stat`, x.`val` FROM `tmp_155p_items` t JOIN `item_template` i ON i.`entry` = t.`entry`
JOIN LATERAL (SELECT i.`stat_type1` AS `stat`, i.`stat_value1` AS `val` UNION ALL SELECT i.`stat_type2`, i.`stat_value2`
  UNION ALL SELECT i.`stat_type3`, i.`stat_value3` UNION ALL SELECT i.`stat_type4`, i.`stat_value4`
  UNION ALL SELECT i.`stat_type5`, i.`stat_value5` UNION ALL SELECT i.`stat_type6`, i.`stat_value6`
  UNION ALL SELECT i.`stat_type7`, i.`stat_value7` UNION ALL SELECT i.`stat_type8`, i.`stat_value8`
  UNION ALL SELECT i.`stat_type9`, i.`stat_value9` UNION ALL SELECT i.`stat_type10`, i.`stat_value10`) x
WHERE t.`kind` = 'b' AND x.`val` > 0;
DROP TABLE IF EXISTS `tmp_155p_ranked`;
CREATE TABLE `tmp_155p_ranked` SELECT `entry`, `stat`, ROW_NUMBER() OVER (PARTITION BY `entry` ORDER BY `val` DESC, `stat`) AS `r` FROM `tmp_155p_stats`;
UPDATE `tmp_155p_items` t JOIN `tmp_155p_ranked` r ON r.`entry` = t.`entry` AND r.`r` = 1 SET t.`top1` = r.`stat`;
UPDATE `tmp_155p_items` t JOIN `tmp_155p_ranked` r ON r.`entry` = t.`entry` AND r.`r` = 2 SET t.`top2` = r.`stat`;
UPDATE `tmp_155p_items` SET `top2` = `top1` WHERE `kind` = 'b' AND `top2` = 0;

-- ---- 5. colours -------------------------------------------------------------------------------
-- socket colours: 2 red, 4 yellow, 8 blue, 14 prismatic. A stat's gem colour:
-- red Strength (4), Agility (3), attack power (38, 39), spell power (45) and
-- the old spell damage/healing (41, 42); blue Stamina (7), Spirit (6),
-- resilience (35), mana (43) and health (46) regeneration; yellow the rest.
DROP TABLE IF EXISTS `tmp_155p_sockets`;
CREATE TABLE `tmp_155p_sockets` (`entry` int unsigned NOT NULL, `n` tinyint unsigned NOT NULL, `color` tinyint unsigned NOT NULL DEFAULT 0, PRIMARY KEY (`entry`, `n`));
INSERT INTO `tmp_155p_sockets` (`entry`, `n`)
SELECT t.`entry`, k.`n` FROM `tmp_155p_items` t JOIN (SELECT 1 AS `n` UNION ALL SELECT 2 UNION ALL SELECT 3) k ON k.`n` <= t.`sockets`;
-- whites' armor: red, yellow, blue in turn across each set, slot by slot
DROP TABLE IF EXISTS `tmp_155p_turn`;
CREATE TABLE `tmp_155p_turn` SELECT s.`entry`, s.`n`,
  ROW_NUMBER() OVER (PARTITION BY t.`setkey` ORDER BY t.`inv`, t.`entry`, s.`n`) - 1 AS `k`
FROM `tmp_155p_sockets` s JOIN `tmp_155p_items` t ON t.`entry` = s.`entry` WHERE t.`kind` = 'w' AND NOT t.`weapon`;
UPDATE `tmp_155p_sockets` s JOIN `tmp_155p_turn` u ON u.`entry` = s.`entry` AND u.`n` = s.`n`
SET s.`color` = ELT(u.`k` % 3 + 1, 2, 4, 8);
-- blues' armor: first socket its strongest stat's colour, second its next
UPDATE `tmp_155p_sockets` s JOIN `tmp_155p_items` t ON t.`entry` = s.`entry`
SET s.`color` = CASE WHEN (IF(s.`n` = 1, t.`top1`, t.`top2`)) IN (3, 4, 38, 39, 41, 42, 45) THEN 2
                     WHEN (IF(s.`n` = 1, t.`top1`, t.`top2`)) IN (6, 7, 35, 43, 46) THEN 8 ELSE 4 END
WHERE t.`kind` = 'b' AND NOT t.`weapon`;
UPDATE `tmp_155p_sockets` s JOIN `tmp_155p_items` t ON t.`entry` = s.`entry` SET s.`color` = 14 WHERE t.`weapon`;

-- ---- 6. the bonus enchantment ----------------------------------------------------------------
-- whites Stamina, blues their strongest stat; the honest enchantment of that
-- stat at the size, or the largest one below it
DROP TABLE IF EXISTS `tmp_155p_pick`;
CREATE TABLE `tmp_155p_pick` (`entry` int unsigned NOT NULL, `enchant` int unsigned NULL, PRIMARY KEY (`entry`));
INSERT INTO `tmp_155p_pick`
SELECT t.`entry`, (SELECT b.`enchant` FROM `tmp_155p_bonus` b
                   WHERE b.`stat` = IF(t.`kind` = 'w', 7, t.`top1`) AND b.`amount` <= t.`bonus`
                   ORDER BY b.`amount` DESC, b.`enchant` LIMIT 1)
FROM `tmp_155p_items` t WHERE t.`bonus` > 0;
-- (no honest enchantment of that stat small enough: no bonus)
DELETE FROM `tmp_155p_pick` WHERE `enchant` IS NULL;

-- ---- 7. save, then write ----------------------------------------------------------------------
INSERT INTO `basic_155p_socket_backup`
SELECT i.`entry`, i.`socketColor_1`, i.`socketColor_2`, i.`socketColor_3`, i.`socketBonus`,
       i.`stat_value1`, i.`stat_value2`, i.`stat_value3`, i.`stat_value4`, i.`stat_value5`,
       i.`stat_value6`, i.`stat_value7`, i.`stat_value8`, i.`stat_value9`, i.`stat_value10`
FROM `item_template` i JOIN `tmp_155p_items` t ON t.`entry` = i.`entry`;
UPDATE `item_template` i JOIN `tmp_155p_items` t ON t.`entry` = i.`entry` SET
  i.`socketColor_1` = COALESCE((SELECT s.`color` FROM `tmp_155p_sockets` s WHERE s.`entry` = t.`entry` AND s.`n` = 1), 0),
  i.`socketColor_2` = COALESCE((SELECT s.`color` FROM `tmp_155p_sockets` s WHERE s.`entry` = t.`entry` AND s.`n` = 2), 0),
  i.`socketColor_3` = COALESCE((SELECT s.`color` FROM `tmp_155p_sockets` s WHERE s.`entry` = t.`entry` AND s.`n` = 3), 0),
  i.`socketBonus`   = COALESCE((SELECT p.`enchant` FROM `tmp_155p_pick` p WHERE p.`entry` = t.`entry`), 0);
-- the blues' fixed stats shrink to what they keep (a stat never to zero)
UPDATE `item_template` i JOIN `tmp_155p_items` t ON t.`entry` = i.`entry` SET
  i.`stat_value1`  = IF(i.`stat_value1`  > 0, GREATEST(1, ROUND(i.`stat_value1`  * t.`keep`)), i.`stat_value1`),
  i.`stat_value2`  = IF(i.`stat_value2`  > 0, GREATEST(1, ROUND(i.`stat_value2`  * t.`keep`)), i.`stat_value2`),
  i.`stat_value3`  = IF(i.`stat_value3`  > 0, GREATEST(1, ROUND(i.`stat_value3`  * t.`keep`)), i.`stat_value3`),
  i.`stat_value4`  = IF(i.`stat_value4`  > 0, GREATEST(1, ROUND(i.`stat_value4`  * t.`keep`)), i.`stat_value4`),
  i.`stat_value5`  = IF(i.`stat_value5`  > 0, GREATEST(1, ROUND(i.`stat_value5`  * t.`keep`)), i.`stat_value5`),
  i.`stat_value6`  = IF(i.`stat_value6`  > 0, GREATEST(1, ROUND(i.`stat_value6`  * t.`keep`)), i.`stat_value6`),
  i.`stat_value7`  = IF(i.`stat_value7`  > 0, GREATEST(1, ROUND(i.`stat_value7`  * t.`keep`)), i.`stat_value7`),
  i.`stat_value8`  = IF(i.`stat_value8`  > 0, GREATEST(1, ROUND(i.`stat_value8`  * t.`keep`)), i.`stat_value8`),
  i.`stat_value9`  = IF(i.`stat_value9`  > 0, GREATEST(1, ROUND(i.`stat_value9`  * t.`keep`)), i.`stat_value9`),
  i.`stat_value10` = IF(i.`stat_value10` > 0, GREATEST(1, ROUND(i.`stat_value10` * t.`keep`)), i.`stat_value10`)
WHERE t.`kind` = 'b';

-- kept for the post-install checks
DROP TABLE IF EXISTS `basic_155p_socketed`;
CREATE TABLE `basic_155p_socketed` ENGINE=InnoDB COMMENT='issue 155p: every item stage 3 socketed, with its plan (read by scripts/validate-basic-state)'
SELECT `entry`, `kind`, `weapon`, `size`, `lvl`, `setkey`, `gem`, `g`, `total`, `sockets`, `bonus`, `keep` FROM `tmp_155p_items`;

DROP TABLE `tmp_155p_pick`;
DROP TABLE `tmp_155p_turn`;
DROP TABLE `tmp_155p_sockets`;
DROP TABLE `tmp_155p_ranked`;
DROP TABLE `tmp_155p_stats`;
DROP TABLE `tmp_155p_table`;
DROP TABLE `tmp_155p_loot`;
DROP TABLE `tmp_155p_step`;
DROP TABLE `tmp_155p_src`;
DROP TABLE `tmp_155p_items`;
DROP TABLE `tmp_155p_green`;
DROP TABLE `tmp_155p_slot`;
DROP TABLE `tmp_155p_capitals`;
DROP TABLE `tmp_155p_dungeons`;
DROP TABLE `tmp_155p_bonus`;

-- ============================================================================
-- End of 20-sockets.sql (apply)
-- ============================================================================
