-- MARKER_E043_APPLY basic-buddy-selector
-- ============================================================================
-- 26-buddy-selector.sql (issue 617b) — APPLY SOURCE
-- ============================================================================
-- Sargobras, the buddy selector. Two creatures share his look (Lord Gregor
-- Lescovar's stand-in, like the Sargobras at Acherus, until 617f chooses):
--
--   6170001  the valley Sargobras: one stands a few steps in front of where
--            new characters arrive in each of the eight starting valleys,
--            for the first buddy (every new character owes one; 617a2).
--   6170002  the wandering Sargobras: never spawned from the database; the
--            Lua script (src/lua-basic/sargobras.lua) summons one near an
--            owner who is owed a buddy, at each tenth level and at login.
--
-- Both talk through the Lua script (gossip hooks on these entries). Texts:
--   6170001  greeting to someone owed a buddy
--   6170002  the wandering Sargobras, to someone who isn't his owner
--   6170003  to someone owed nothing
--
-- Creatures 6170001-6170002, valley spawns 61700001-61700008, texts
-- 6170001-6170003. Re-applicable: each apply first removes what an earlier
-- one added. Database: acore_world_basic. Applied by E043.
-- ============================================================================

DELETE FROM `creature`                WHERE `guid`       BETWEEN 61700001 AND 61700099;
DELETE FROM `creature_template_model` WHERE `CreatureID` BETWEEN 6170001  AND 6170002;
DELETE FROM `creature_template`       WHERE `entry`      BETWEEN 6170001  AND 6170002;
DELETE FROM `npc_text`                WHERE `ID`         BETWEEN 6170001  AND 6170003;

-- two copies of Lord Gregor Lescovar (1754): gossip only, friendly to all
DROP TEMPORARY TABLE IF EXISTS `tmp_617b_template`;
CREATE TEMPORARY TABLE `tmp_617b_template` AS SELECT * FROM `creature_template` WHERE `entry` = 1754;
UPDATE `tmp_617b_template` SET
  `entry` = 6170001, `name` = 'Sargobras', `subname` = '', `npcflag` = 1,
  `difficulty_entry_1` = 0, `difficulty_entry_2` = 0, `difficulty_entry_3` = 0, `KillCredit1` = 0, `KillCredit2` = 0,
  `faction` = 35, `gossip_menu_id` = 0, `minlevel` = 80, `maxlevel` = 80,
  `lootid` = 0, `pickpocketloot` = 0, `skinloot` = 0, `AIName` = '', `ScriptName` = '';
INSERT INTO `creature_template` SELECT * FROM `tmp_617b_template`;
UPDATE `tmp_617b_template` SET `entry` = 6170002;
INSERT INTO `creature_template` SELECT * FROM `tmp_617b_template`;
DROP TEMPORARY TABLE `tmp_617b_template`;
DROP TEMPORARY TABLE IF EXISTS `tmp_617b_model`;
CREATE TEMPORARY TABLE `tmp_617b_model` AS SELECT * FROM `creature_template_model` WHERE `CreatureID` = 1754;
UPDATE `tmp_617b_model` SET `CreatureID` = 6170001;
INSERT INTO `creature_template_model` SELECT * FROM `tmp_617b_model`;
UPDATE `tmp_617b_model` SET `CreatureID` = 6170002;
INSERT INTO `creature_template_model` SELECT * FROM `tmp_617b_model`;
DROP TEMPORARY TABLE `tmp_617b_model`;

INSERT INTO `npc_text` (`ID`, `text0_0`, `text0_1`, `Probability0`) VALUES
  (6170001, 'Every hero needs someone to blame when things go wrong. Pick a class, or a people, and I will find you a friend.',
            'Every hero needs someone to blame when things go wrong. Pick a class, or a people, and I will find you a friend.', 1),
  (6170002, 'I am spoken for, I am afraid. Someone else is waiting on my advice.',
            'I am spoken for, I am afraid. Someone else is waiting on my advice.', 1),
  (6170003, 'You have all the friends I can find you, for now. Come see me when you have grown a little.',
            'You have all the friends I can find you, for now. Come see me when you have grown a little.', 1);

-- >>> GENERATED by scripts/generate-basic-buddy-selector-sql
-- one per starting valley: 4 yards ahead of the arrival point, facing it
INSERT INTO `creature` (`guid`, `id`, `map`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `Comment`) VALUES
  (61700001, 6170001, 0, 1, 1, -6236.3, 331.0, 382.8, 3.14, 300, 'issue 617b: valley Sargobras, zone 1 (races 3,7)'),
  (61700002, 6170001, 0, 1, 1, -8946.0, -132.5, 83.5, 3.14, 300, 'issue 617b: valley Sargobras, zone 12 (races 1)'),
  (61700003, 6170001, 0, 1, 1, 1673.1, 1680.0, 121.7, 5.85, 300, 'issue 617b: valley Sargobras, zone 85 (races 5)'),
  (61700004, 6170001, 1, 1, 1, -614.5, -4251.7, 38.7, 3.14, 300, 'issue 617b: valley Sargobras, zone 14 (races 2,8)'),
  (61700005, 6170001, 1, 1, 1, 10314.6, 830.2, 1326.4, 2.55, 300, 'issue 617b: valley Sargobras, zone 141 (races 4)'),
  (61700006, 6170001, 1, 1, 1, -2913.6, -258.0, 53.0, 3.14, 300, 'issue 617b: valley Sargobras, zone 215 (races 6)'),
  (61700007, 6170001, 530, 1, 1, 10351.9, -6360.6, 33.4, 2.17, 300, 'issue 617b: valley Sargobras, zone 3431 (races 10)'),
  (61700008, 6170001, 530, 1, 1, -3963.6, -13927.7, 100.6, 5.23, 300, 'issue 617b: valley Sargobras, zone 3526 (races 11)');
-- <<< GENERATED END

-- ============================================================================
-- End of 26-buddy-selector.sql (apply)
-- ============================================================================
