-- MARKER_E048_APPLY basic-buddy-kit-required-level
-- GENERATED by scripts/generate-buddy-kit-tiers; don't edit by hand.
-- Issue 617a4. A buddy's gear tier is worn from the tier's level, so a
-- tier item whose required level is above that level comes down to it.
-- Only those items move; the originals are saved first (INSERT IGNORE: a
-- re-apply never overwrites them) and the revert restores them exactly.
-- These are ordinary world items: players on basic can wear them from the
-- same level too.
CREATE TABLE IF NOT EXISTS `basic_617a4_kit_originals` (
    `entry`         INT UNSIGNED     NOT NULL PRIMARY KEY,
    `RequiredLevel` TINYINT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='617a4: required levels before the buddy kit tiers lowered them';

-- tier 20: 46 items
INSERT IGNORE INTO basic_617a4_kit_originals (entry, RequiredLevel)
  SELECT entry, RequiredLevel FROM item_template WHERE RequiredLevel > 20 AND entry IN (853, 922, 924, 925, 926, 1159, 1197, 1198, 1292, 2027, 2030, 2141, 2142, 2143, 2144, 2145, 2146, 2148, 2149, 2150, 2151, 2152, 2153, 2156, 2158, 2159, 2160, 2240, 2441, 2445, 2515, 3027, 3422, 3445, 3591, 3592, 4238, 5210, 5211, 5580, 6948, 11362, 15810, 19295, 23923, 46978);
UPDATE item_template SET RequiredLevel = 20 WHERE RequiredLevel > 20 AND entry IN (853, 922, 924, 925, 926, 1159, 1197, 1198, 1292, 2027, 2030, 2141, 2142, 2143, 2144, 2145, 2146, 2148, 2149, 2150, 2151, 2152, 2153, 2156, 2158, 2159, 2160, 2240, 2441, 2445, 2515, 3027, 3422, 3445, 3591, 3592, 4238, 5210, 5211, 5580, 6948, 11362, 15810, 19295, 23923, 46978);
