-- MARKER_E048_REVERT basic-buddy-kit-required-level
-- GENERATED by scripts/generate-buddy-kit-tiers; don't edit by hand.
-- Restores the saved required levels, then drops the saved copy.
UPDATE item_template it JOIN basic_617a4_kit_originals o ON o.entry = it.entry SET it.RequiredLevel = o.RequiredLevel;
DROP TABLE IF EXISTS basic_617a4_kit_originals;
