-- MARKER_E009_APPLY vanilla-starting-equipment
-- AUTOGENERATED by scripts/generate-vanilla-starting-equipment-sql.
-- Do not edit by hand — change the generator and re-run.
--
-- Apply-form SOURCE for E009. The E-patch cp's this file to
-- sql/vanilla/db_world/02-starting-equipment.sql, which AC's
-- UpdateFetcher picks up on next worldserver boot.
--
-- Purpose: equip every newly-created vanilla character (level-20 start
-- per C007c) with a full white-quality, race-and-class-appropriate
-- starter kit per the 148h thematic-curation design. References cloned
-- item entries (original_entry + 2000000) created by the E018 patch.
--
-- Idempotent: re-running deletes prior vanilla-148h rows by Note prefix
-- and re-inserts. Default shirt/pants/quest-starter rows untouched.
--
-- Dual Wield dependency: dual-wield kits (Orc/Troll Hunter dual cleavers,
-- Gnome Warrior twin Scimitars, every Rogue's twin-dagger or mixed-
-- pair kit) need spell 674 "Dual Wield" granted before the off-hand
-- can equip. 148j grants every level-≤20 trainer spell at creation,
-- including DW.
--
-- Cross-references:
--   issues/148h-class-specific-starting-equipment.md  -- behavior spec
--   issues/148j-pretrain-level-20-abilities.md        -- DW dependency
--   issues/148k-ale-auto-equip-starter-kit.md         -- equip hook
--   issues/148n-vanilla-racial-starting-zones.md      -- bind targets
--   issues/148o-vanilla-spawn-and-kit-validation-pass.md -- test pass
--   issues/148p-wand-spell-dps-parity-rebalance.md    -- wand follow-up
--   sql/vanilla/db_world.src/06-kit-required-level-cap.apply.sql  -- clones

START TRANSACTION;

-- {{{ idempotence_clear
DELETE FROM playercreateinfo_item
 WHERE Note LIKE 'vanilla-148h-%'
    OR Note = 'vanilla starter kit';

DELETE FROM playercreateinfo_skills
 WHERE comment LIKE 'vanilla-148h-%'
    OR comment LIKE 'vanilla starter %';
-- }}}

-- {{{ playercreateinfo_item — per (race, class) starter kit

-- warrior (class 1)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 2002153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 2002152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 2002151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 2002149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 2002148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 2002150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 2001198, 1, 'vanilla-148h-mainhand-2h-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 2006948, 1, 'vanilla-148h-hearthstone');

-- paladin (class 2)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 2, 2002153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 2, 2002152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 2, 2002151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 2, 2002149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 2, 2002148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 2, 2002150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 2, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 2, 2000924, 1, 'vanilla-148h-mainhand-2h-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 2, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 2, 2006948, 1, 'vanilla-148h-hearthstone');

-- rogue (class 4)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 4, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 4, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 4, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 4, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 4, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 4, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 4, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 4, 2003445, 2, 'vanilla-148h-dualwield-daggers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 4, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 4, 2006948, 1, 'vanilla-148h-hearthstone');

-- priest (class 5)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 2002160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 2002159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 2002158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 2002156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 2003591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 2003592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 2005580, 1, 'vanilla-148h-mainhand-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 2003422, 1, 'vanilla-148h-offhand-wildflowers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 2005211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 2006948, 1, 'vanilla-148h-hearthstone');

-- mage (class 8)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 2002160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 2002159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 2002158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 2002156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 2003591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 2003592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 2001159, 1, 'vanilla-148h-mainhand-staff');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 2005210, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 2006948, 1, 'vanilla-148h-hearthstone');

-- warlock (class 9)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 2002160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 2002159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 2002158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 2002156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 2003591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 2003592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 2002027, 1, 'vanilla-148h-mainhand-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 2019295, 1, 'vanilla-148h-offhand-flower');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 2005211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 2006948, 1, 'vanilla-148h-hearthstone');

-- warrior (class 1)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 2002153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 2002152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 2002151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 2002149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 2002148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 2002150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 2000853, 1, 'vanilla-148h-mainhand-axe');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 2002441, 1, 'vanilla-148h-offhand-shield');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 2006948, 1, 'vanilla-148h-hearthstone');

-- hunter (class 3)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2001292, 2, 'vanilla-148h-dualwield-cleavers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2003027, 1, 'vanilla-148h-ranged-bow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2002515, 200, 'vanilla-148h-ammo-arrow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2011362, 1, 'vanilla-148h-quiver');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2006948, 1, 'vanilla-148h-hearthstone');

-- rogue (class 4)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 2000925, 1, 'vanilla-148h-mainhand-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 2003445, 1, 'vanilla-148h-offhand-dagger');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 2006948, 1, 'vanilla-148h-hearthstone');

-- shaman (class 7)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 2001197, 1, 'vanilla-148h-mainhand-2h-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 2046978, 1, 'vanilla-148h-relic-totem');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 2006948, 1, 'vanilla-148h-hearthstone');

-- warlock (class 9)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 2002160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 2002159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 2002158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 2002156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 2003591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 2003592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 2001159, 1, 'vanilla-148h-mainhand-staff');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 2005210, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 2006948, 1, 'vanilla-148h-hearthstone');

-- warrior (class 1)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 2002153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 2002152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 2002151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 2002149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 2002148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 2002150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 2015810, 1, 'vanilla-148h-mainhand-polearm');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 2006948, 1, 'vanilla-148h-hearthstone');

-- paladin (class 2)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 2002153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 2002152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 2002151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 2002149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 2002148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 2002150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 2000925, 1, 'vanilla-148h-mainhand-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 2002445, 1, 'vanilla-148h-offhand-shield');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 2006948, 1, 'vanilla-148h-hearthstone');

-- hunter (class 3)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2000926, 1, 'vanilla-148h-mainhand-2h-axe');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2003027, 1, 'vanilla-148h-ranged-bow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2002515, 200, 'vanilla-148h-ammo-arrow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2011362, 1, 'vanilla-148h-quiver');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2006948, 1, 'vanilla-148h-hearthstone');

-- rogue (class 4)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 4, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 4, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 4, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 4, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 4, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 4, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 4, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 4, 2003445, 2, 'vanilla-148h-dualwield-daggers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 4, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 4, 2006948, 1, 'vanilla-148h-hearthstone');

-- priest (class 5)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 2002160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 2002159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 2002158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 2002156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 2003591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 2003592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 2005580, 1, 'vanilla-148h-mainhand-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 2003422, 1, 'vanilla-148h-offhand-wildflowers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 2005211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 2006948, 1, 'vanilla-148h-hearthstone');

-- warrior (class 1)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 1, 2002153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 1, 2002152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 1, 2002151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 1, 2002149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 1, 2002148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 1, 2002150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 1, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 1, 2015810, 1, 'vanilla-148h-mainhand-polearm');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 1, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 1, 2006948, 1, 'vanilla-148h-hearthstone');

-- hunter (class 3)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2000922, 1, 'vanilla-148h-mainhand-polearm');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2003027, 1, 'vanilla-148h-ranged-bow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2002515, 200, 'vanilla-148h-ammo-arrow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2011362, 1, 'vanilla-148h-quiver');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2006948, 1, 'vanilla-148h-hearthstone');

-- rogue (class 4)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 4, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 4, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 4, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 4, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 4, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 4, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 4, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 4, 2002027, 2, 'vanilla-148h-dualwield-swords');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 4, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 4, 2006948, 1, 'vanilla-148h-hearthstone');

-- priest (class 5)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 2002160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 2002159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 2002158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 2002156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 2003591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 2003592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 2002030, 1, 'vanilla-148h-mainhand-staff');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 2005211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 2006948, 1, 'vanilla-148h-hearthstone');

-- druid (class 11)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 11, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 11, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 11, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 11, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 11, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 11, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 11, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 11, 2001159, 1, 'vanilla-148h-mainhand-staff');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 11, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 11, 2006948, 1, 'vanilla-148h-hearthstone');

-- warrior (class 1)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 2002153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 2002152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 2002151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 2002149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 2002148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 2002150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 2000926, 1, 'vanilla-148h-mainhand-2h-axe');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 2006948, 1, 'vanilla-148h-hearthstone');

-- rogue (class 4)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 2002027, 1, 'vanilla-148h-mainhand-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 2003445, 1, 'vanilla-148h-offhand-dagger');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 2006948, 1, 'vanilla-148h-hearthstone');

-- priest (class 5)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 2002160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 2002159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 2002158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 2002156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 2003591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 2003592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 2023923, 1, 'vanilla-148h-mainhand-dagger');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 2003422, 1, 'vanilla-148h-offhand-wildflowers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 2005211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 2006948, 1, 'vanilla-148h-hearthstone');

-- mage (class 8)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 2002160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 2002159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 2002158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 2002156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 2003591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 2003592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 2002030, 1, 'vanilla-148h-mainhand-staff');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 2005210, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 2006948, 1, 'vanilla-148h-hearthstone');

-- warlock (class 9)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 2002160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 2002159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 2002158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 2002156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 2003591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 2003592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 2002027, 1, 'vanilla-148h-mainhand-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 2019295, 1, 'vanilla-148h-offhand-flower');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 2005210, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 2006948, 1, 'vanilla-148h-hearthstone');

-- warrior (class 1)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 2002153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 2002152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 2002151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 2002149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 2002148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 2002150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 2015810, 1, 'vanilla-148h-mainhand-polearm');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 2006948, 1, 'vanilla-148h-hearthstone');

-- hunter (class 3)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2002030, 1, 'vanilla-148h-mainhand-staff');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2003027, 1, 'vanilla-148h-ranged-bow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2002515, 200, 'vanilla-148h-ammo-arrow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2011362, 1, 'vanilla-148h-quiver');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2006948, 1, 'vanilla-148h-hearthstone');

-- shaman (class 7)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 2001197, 1, 'vanilla-148h-mainhand-2h-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 2046978, 1, 'vanilla-148h-relic-totem');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 2006948, 1, 'vanilla-148h-hearthstone');

-- druid (class 11)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 11, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 11, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 11, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 11, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 11, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 11, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 11, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 11, 2001159, 1, 'vanilla-148h-mainhand-staff');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 11, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 11, 2006948, 1, 'vanilla-148h-hearthstone');

-- warrior (class 1)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 2002153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 2002152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 2002151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 2002149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 2002148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 2002150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 2002027, 2, 'vanilla-148h-dualwield-swords');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 2006948, 1, 'vanilla-148h-hearthstone');

-- rogue (class 4)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 4, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 4, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 4, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 4, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 4, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 4, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 4, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 4, 2003445, 2, 'vanilla-148h-dualwield-daggers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 4, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 4, 2006948, 1, 'vanilla-148h-hearthstone');

-- mage (class 8)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 2002160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 2002159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 2002158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 2002156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 2003591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 2003592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 2002030, 1, 'vanilla-148h-mainhand-staff');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 2005210, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 2006948, 1, 'vanilla-148h-hearthstone');

-- warlock (class 9)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 2002160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 2002159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 2002158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 2002156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 2003591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 2003592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 2002027, 1, 'vanilla-148h-mainhand-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 2019295, 1, 'vanilla-148h-offhand-flower');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 2005211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 2006948, 1, 'vanilla-148h-hearthstone');

-- warrior (class 1)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 1, 2002153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 1, 2002152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 1, 2002151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 1, 2002149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 1, 2002148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 1, 2002150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 1, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 1, 2000926, 1, 'vanilla-148h-mainhand-2h-axe');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 1, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 1, 2006948, 1, 'vanilla-148h-hearthstone');

-- hunter (class 3)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2001292, 2, 'vanilla-148h-dualwield-cleavers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2003027, 1, 'vanilla-148h-ranged-bow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2002515, 200, 'vanilla-148h-ammo-arrow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2011362, 1, 'vanilla-148h-quiver');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2006948, 1, 'vanilla-148h-hearthstone');

-- rogue (class 4)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 4, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 4, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 4, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 4, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 4, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 4, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 4, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 4, 2003445, 2, 'vanilla-148h-dualwield-daggers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 4, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 4, 2006948, 1, 'vanilla-148h-hearthstone');

-- priest (class 5)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 2002160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 2002159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 2002158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 2002156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 2003591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 2003592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 2000925, 1, 'vanilla-148h-mainhand-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 2003422, 1, 'vanilla-148h-offhand-wildflowers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 2005211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 2006948, 1, 'vanilla-148h-hearthstone');

-- shaman (class 7)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 2000926, 1, 'vanilla-148h-mainhand-2h-axe');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 2046978, 1, 'vanilla-148h-relic-totem');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 2006948, 1, 'vanilla-148h-hearthstone');

-- mage (class 8)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 8, 2002160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 8, 2002159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 8, 2002158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 8, 2002156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 8, 2003591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 8, 2003592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 8, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 8, 2023923, 1, 'vanilla-148h-mainhand-dagger');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 8, 2019295, 1, 'vanilla-148h-offhand-flower');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 8, 2005210, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 8, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 8, 2006948, 1, 'vanilla-148h-hearthstone');

-- paladin (class 2)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 2, 2002153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 2, 2002152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 2, 2002151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 2, 2002149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 2, 2002148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 2, 2002150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 2, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 2, 2001198, 1, 'vanilla-148h-mainhand-2h-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 2, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 2, 2006948, 1, 'vanilla-148h-hearthstone');

-- hunter (class 3)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2015810, 1, 'vanilla-148h-mainhand-polearm');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2003027, 1, 'vanilla-148h-ranged-bow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2002515, 200, 'vanilla-148h-ammo-arrow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2011362, 1, 'vanilla-148h-quiver');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2006948, 1, 'vanilla-148h-hearthstone');

-- rogue (class 4)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 4, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 4, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 4, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 4, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 4, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 4, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 4, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 4, 2002027, 2, 'vanilla-148h-dualwield-swords');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 4, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 4, 2006948, 1, 'vanilla-148h-hearthstone');

-- priest (class 5)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 2002160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 2002159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 2002158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 2002156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 2003591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 2003592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 2023923, 1, 'vanilla-148h-mainhand-dagger');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 2003422, 1, 'vanilla-148h-offhand-wildflowers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 2005211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 2006948, 1, 'vanilla-148h-hearthstone');

-- mage (class 8)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 2002160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 2002159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 2002158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 2002156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 2003591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 2003592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 2002027, 1, 'vanilla-148h-mainhand-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 2019295, 1, 'vanilla-148h-offhand-flower');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 2005210, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 2006948, 1, 'vanilla-148h-hearthstone');

-- warlock (class 9)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 2002160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 2002159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 2002158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 2002156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 2003591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 2003592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 2023923, 1, 'vanilla-148h-mainhand-dagger');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 2019295, 1, 'vanilla-148h-offhand-flower');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 2005210, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 2006948, 1, 'vanilla-148h-hearthstone');

-- warrior (class 1)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 2002153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 2002152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 2002151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 2002149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 2002148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 2002150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 2005580, 1, 'vanilla-148h-mainhand-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 2002445, 1, 'vanilla-148h-offhand-shield');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 2006948, 1, 'vanilla-148h-hearthstone');

-- paladin (class 2)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 2, 2002153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 2, 2002152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 2, 2002151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 2, 2002149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 2, 2002148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 2, 2002150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 2, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 2, 2000924, 1, 'vanilla-148h-mainhand-2h-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 2, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 2, 2006948, 1, 'vanilla-148h-hearthstone');

-- hunter (class 3)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2001198, 1, 'vanilla-148h-mainhand-2h-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2003027, 1, 'vanilla-148h-ranged-bow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2002515, 200, 'vanilla-148h-ammo-arrow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2011362, 1, 'vanilla-148h-quiver');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2006948, 1, 'vanilla-148h-hearthstone');

-- priest (class 5)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 2002160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 2002159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 2002158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 2002156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 2003591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 2003592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 2005580, 1, 'vanilla-148h-mainhand-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 2003422, 1, 'vanilla-148h-offhand-wildflowers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 2005211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 2006948, 1, 'vanilla-148h-hearthstone');

-- shaman (class 7)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 2002141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 2002146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 2002145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 2002143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 2002142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 2002144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 2000853, 1, 'vanilla-148h-mainhand-axe');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 2002445, 1, 'vanilla-148h-offhand-shield');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 2046978, 1, 'vanilla-148h-relic-totem');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 2006948, 1, 'vanilla-148h-hearthstone');

-- mage (class 8)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 2002160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 2002159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 2002158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 2002156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 2003591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 2003592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 2002240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 2002030, 1, 'vanilla-148h-mainhand-staff');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 2005210, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 2004238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 2006948, 1, 'vanilla-148h-hearthstone');
-- }}}

COMMIT;
