-- MARKER_E009_APPLY vanilla-starting-equipment
-- AUTOGENERATED by scripts/generate-vanilla-starting-equipment-sql.
-- Do not edit by hand — change the generator and re-run.
--
-- This file is the apply-form SOURCE for E009. The E-patch (apply
-- direction) cp's this file to ${DIR}/sql/vanilla/db_world/02-starting-equipment.sql,
-- which AC's UpdateFetcher then picks up on next worldserver boot via
-- the include row registered by _register_vanilla_world_dir_once.
-- The unpatch direction overwrites that same active file with an
-- inline revert heredoc; this source file stays intact so the next
-- apply can re-stage it.
--
-- Purpose: equip every newly-created vanilla character (level-20 start
-- per C007c) with a full white-quality class-appropriate starter kit
-- so they can step out of the starting zone immediately playable.
-- Race-specific kit overrides (paladin race variants, hunter race
-- variants, warrior race variants, shaman race variants) handled by
-- the generator; see the matrix at the top of the script.
--
-- Idempotent: re-running deletes prior vanilla-148h rows by Note prefix
-- and re-inserts. Default shirt/pants/quest-starter rows untouched.
--
-- Dual Wield dependency: Orc Hunter's twin-axe kit and every Rogue's
-- twin-dagger kit need spell 674 "Dual Wield" granted before the
-- off-hand can equip. Hunters learn it at level 20 from a trainer;
-- Rogues at level 10. Sub-issue 148j (S5 in the 148 roadmap) grants
-- every level-≤20 trainer spell at creation, including DW, so the
-- off-hand items in this migration become equippable once 148j applies.
-- This migration does NOT include the DW spell grant; it relies on
-- 148j running alongside.
--
-- Cross-references:
--   issues/148h-class-specific-starting-equipment.md   -- behavior spec
--   issues/148j-pretrain-level-20-abilities.md         -- DW dependency
--   tmp/148-parallelization-roadmap.md R7 Results      -- item matrix

START TRANSACTION;

-- {{{ idempotence_clear
-- Clears both this generator's Note prefix (vanilla-148h-*) and the
-- prior cute-robot-session S4's literal-string tag ('vanilla starter
-- kit' / 'vanilla starter %') so re-applying after either version of
-- the migration leaves the same state.
DELETE FROM playercreateinfo_item
 WHERE Note LIKE 'vanilla-148h-%'
    OR Note = 'vanilla starter kit';

DELETE FROM playercreateinfo_skills
 WHERE comment LIKE 'vanilla-148h-%'
    OR comment LIKE 'vanilla starter %';
-- }}}

-- {{{ playercreateinfo_item — per (race, class) starter kit

-- warrior (class 1)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 2153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 2152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 2151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 2149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 2148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 2150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 923, 1, 'vanilla-148h-mainhand-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 2442, 1, 'vanilla-148h-offhand-shield');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 1, 6948, 1, 'vanilla-148h-hearthstone');

-- paladin (class 2)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 2, 2153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 2, 2152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 2, 2151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 2, 2149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 2, 2148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 2, 2150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 2, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 2, 924, 1, 'vanilla-148h-mainhand-2h-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 2, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 2, 6948, 1, 'vanilla-148h-hearthstone');

-- rogue (class 4)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 4, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 4, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 4, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 4, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 4, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 4, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 4, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 4, 2209, 2, 'vanilla-148h-dualwield-daggers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 4, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 4, 6948, 1, 'vanilla-148h-hearthstone');

-- priest (class 5)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 2160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 2159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 2158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 2156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 3591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 3592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 925, 1, 'vanilla-148h-mainhand-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 3422, 1, 'vanilla-148h-offhand-wildflowers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 5211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 5, 6948, 1, 'vanilla-148h-hearthstone');

-- mage (class 8)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 2160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 2159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 2158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 2156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 3591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 3592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 928, 1, 'vanilla-148h-mainhand-staff');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 5211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 8, 6948, 1, 'vanilla-148h-hearthstone');

-- warlock (class 9)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 2160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 2159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 2158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 2156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 3591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 3592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 923, 1, 'vanilla-148h-mainhand-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 19295, 1, 'vanilla-148h-offhand-flower');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 5211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (1, 9, 6948, 1, 'vanilla-148h-hearthstone');

-- warrior (class 1)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 2153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 2152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 2151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 2149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 2148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 2150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 923, 1, 'vanilla-148h-mainhand-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 2442, 1, 'vanilla-148h-offhand-shield');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 1, 6948, 1, 'vanilla-148h-hearthstone');

-- hunter (class 3)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 927, 2, 'vanilla-148h-dualwield-axes');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 3027, 1, 'vanilla-148h-ranged-bow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 2515, 200, 'vanilla-148h-ammo-arrow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 11362, 1, 'vanilla-148h-quiver');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 3, 6948, 1, 'vanilla-148h-hearthstone');

-- rogue (class 4)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 925, 1, 'vanilla-148h-mainhand-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 2209, 1, 'vanilla-148h-offhand-dagger');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 4, 6948, 1, 'vanilla-148h-hearthstone');

-- shaman (class 7)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 925, 1, 'vanilla-148h-mainhand-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 2442, 1, 'vanilla-148h-offhand-shield');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 46978, 1, 'vanilla-148h-relic-totem');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 7, 6948, 1, 'vanilla-148h-hearthstone');

-- warlock (class 9)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 2160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 2159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 2158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 2156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 3591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 3592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 923, 1, 'vanilla-148h-mainhand-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 19295, 1, 'vanilla-148h-offhand-flower');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 5211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (2, 9, 6948, 1, 'vanilla-148h-hearthstone');

-- warrior (class 1)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 2153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 2152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 2151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 2149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 2148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 2150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 923, 1, 'vanilla-148h-mainhand-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 2442, 1, 'vanilla-148h-offhand-shield');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 1, 6948, 1, 'vanilla-148h-hearthstone');

-- paladin (class 2)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 2153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 2152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 2151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 2149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 2148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 2150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 925, 1, 'vanilla-148h-mainhand-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 2442, 1, 'vanilla-148h-offhand-shield');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 2, 6948, 1, 'vanilla-148h-hearthstone');

-- hunter (class 3)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 923, 1, 'vanilla-148h-mainhand-melee');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 3027, 1, 'vanilla-148h-ranged-bow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 2515, 200, 'vanilla-148h-ammo-arrow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 11362, 1, 'vanilla-148h-quiver');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 3, 6948, 1, 'vanilla-148h-hearthstone');

-- rogue (class 4)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 4, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 4, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 4, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 4, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 4, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 4, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 4, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 4, 2209, 2, 'vanilla-148h-dualwield-daggers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 4, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 4, 6948, 1, 'vanilla-148h-hearthstone');

-- priest (class 5)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 2160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 2159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 2158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 2156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 3591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 3592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 925, 1, 'vanilla-148h-mainhand-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 3422, 1, 'vanilla-148h-offhand-wildflowers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 5211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (3, 5, 6948, 1, 'vanilla-148h-hearthstone');

-- warrior (class 1)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 1, 2153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 1, 2152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 1, 2151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 1, 2149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 1, 2148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 1, 2150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 1, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 1, 15810, 1, 'vanilla-148h-mainhand-polearm');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 1, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 1, 6948, 1, 'vanilla-148h-hearthstone');

-- hunter (class 3)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 923, 1, 'vanilla-148h-mainhand-melee');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 3027, 1, 'vanilla-148h-ranged-bow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 2515, 200, 'vanilla-148h-ammo-arrow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 11362, 1, 'vanilla-148h-quiver');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 3, 6948, 1, 'vanilla-148h-hearthstone');

-- rogue (class 4)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 4, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 4, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 4, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 4, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 4, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 4, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 4, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 4, 923, 2, 'vanilla-148h-dualwield-swords');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 4, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 4, 6948, 1, 'vanilla-148h-hearthstone');

-- priest (class 5)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 2160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 2159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 2158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 2156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 3591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 3592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 925, 1, 'vanilla-148h-mainhand-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 3422, 1, 'vanilla-148h-offhand-wildflowers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 5211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 5, 6948, 1, 'vanilla-148h-hearthstone');

-- druid (class 11)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 11, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 11, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 11, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 11, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 11, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 11, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 11, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 11, 928, 1, 'vanilla-148h-mainhand-staff');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 11, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (4, 11, 6948, 1, 'vanilla-148h-hearthstone');

-- warrior (class 1)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 2153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 2152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 2151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 2149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 2148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 2150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 923, 1, 'vanilla-148h-mainhand-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 2442, 1, 'vanilla-148h-offhand-shield');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 1, 6948, 1, 'vanilla-148h-hearthstone');

-- rogue (class 4)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 923, 1, 'vanilla-148h-mainhand-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 2209, 1, 'vanilla-148h-offhand-dagger');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 4, 6948, 1, 'vanilla-148h-hearthstone');

-- priest (class 5)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 2160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 2159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 2158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 2156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 3591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 3592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 925, 1, 'vanilla-148h-mainhand-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 3422, 1, 'vanilla-148h-offhand-wildflowers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 5211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 5, 6948, 1, 'vanilla-148h-hearthstone');

-- mage (class 8)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 2160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 2159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 2158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 2156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 3591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 3592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 928, 1, 'vanilla-148h-mainhand-staff');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 5211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 8, 6948, 1, 'vanilla-148h-hearthstone');

-- warlock (class 9)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 2160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 2159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 2158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 2156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 3591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 3592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 923, 1, 'vanilla-148h-mainhand-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 19295, 1, 'vanilla-148h-offhand-flower');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 5211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (5, 9, 6948, 1, 'vanilla-148h-hearthstone');

-- warrior (class 1)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 2153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 2152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 2151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 2149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 2148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 2150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 923, 1, 'vanilla-148h-mainhand-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 2442, 1, 'vanilla-148h-offhand-shield');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 1, 6948, 1, 'vanilla-148h-hearthstone');

-- hunter (class 3)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 923, 1, 'vanilla-148h-mainhand-melee');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 3027, 1, 'vanilla-148h-ranged-bow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 2515, 200, 'vanilla-148h-ammo-arrow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 11362, 1, 'vanilla-148h-quiver');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 3, 6948, 1, 'vanilla-148h-hearthstone');

-- shaman (class 7)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 924, 1, 'vanilla-148h-mainhand-2h-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 46978, 1, 'vanilla-148h-relic-totem');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 7, 6948, 1, 'vanilla-148h-hearthstone');

-- druid (class 11)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 11, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 11, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 11, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 11, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 11, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 11, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 11, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 11, 928, 1, 'vanilla-148h-mainhand-staff');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 11, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (6, 11, 6948, 1, 'vanilla-148h-hearthstone');

-- warrior (class 1)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 2153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 2152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 2151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 2149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 2148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 2150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 923, 1, 'vanilla-148h-mainhand-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 2442, 1, 'vanilla-148h-offhand-shield');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 1, 6948, 1, 'vanilla-148h-hearthstone');

-- rogue (class 4)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 4, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 4, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 4, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 4, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 4, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 4, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 4, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 4, 2209, 2, 'vanilla-148h-dualwield-daggers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 4, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 4, 6948, 1, 'vanilla-148h-hearthstone');

-- mage (class 8)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 2160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 2159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 2158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 2156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 3591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 3592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 928, 1, 'vanilla-148h-mainhand-staff');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 5211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 8, 6948, 1, 'vanilla-148h-hearthstone');

-- warlock (class 9)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 2160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 2159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 2158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 2156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 3591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 3592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 923, 1, 'vanilla-148h-mainhand-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 19295, 1, 'vanilla-148h-offhand-flower');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 5211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (7, 9, 6948, 1, 'vanilla-148h-hearthstone');

-- warrior (class 1)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 1, 2153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 1, 2152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 1, 2151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 1, 2149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 1, 2148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 1, 2150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 1, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 1, 926, 1, 'vanilla-148h-mainhand-2h-axe');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 1, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 1, 6948, 1, 'vanilla-148h-hearthstone');

-- hunter (class 3)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 923, 1, 'vanilla-148h-mainhand-melee');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 3027, 1, 'vanilla-148h-ranged-bow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 2515, 200, 'vanilla-148h-ammo-arrow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 11362, 1, 'vanilla-148h-quiver');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 3, 6948, 1, 'vanilla-148h-hearthstone');

-- rogue (class 4)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 4, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 4, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 4, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 4, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 4, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 4, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 4, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 4, 2209, 2, 'vanilla-148h-dualwield-daggers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 4, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 4, 6948, 1, 'vanilla-148h-hearthstone');

-- priest (class 5)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 2160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 2159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 2158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 2156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 3591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 3592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 925, 1, 'vanilla-148h-mainhand-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 3422, 1, 'vanilla-148h-offhand-wildflowers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 5211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 5, 6948, 1, 'vanilla-148h-hearthstone');

-- shaman (class 7)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 926, 1, 'vanilla-148h-mainhand-2h-axe');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 46978, 1, 'vanilla-148h-relic-totem');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (8, 7, 6948, 1, 'vanilla-148h-hearthstone');

-- paladin (class 2)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 2, 2153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 2, 2152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 2, 2151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 2, 2149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 2, 2148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 2, 2150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 2, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 2, 922, 1, 'vanilla-148h-mainhand-2h-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 2, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 2, 6948, 1, 'vanilla-148h-hearthstone');

-- hunter (class 3)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 15810, 1, 'vanilla-148h-mainhand-polearm');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 3027, 1, 'vanilla-148h-ranged-bow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 2515, 200, 'vanilla-148h-ammo-arrow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 11362, 1, 'vanilla-148h-quiver');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 3, 6948, 1, 'vanilla-148h-hearthstone');

-- rogue (class 4)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 4, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 4, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 4, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 4, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 4, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 4, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 4, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 4, 923, 2, 'vanilla-148h-dualwield-swords');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 4, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 4, 6948, 1, 'vanilla-148h-hearthstone');

-- priest (class 5)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 2160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 2159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 2158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 2156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 3591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 3592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 925, 1, 'vanilla-148h-mainhand-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 3422, 1, 'vanilla-148h-offhand-wildflowers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 5211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 5, 6948, 1, 'vanilla-148h-hearthstone');

-- mage (class 8)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 2160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 2159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 2158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 2156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 3591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 3592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 928, 1, 'vanilla-148h-mainhand-staff');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 5211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 8, 6948, 1, 'vanilla-148h-hearthstone');

-- warlock (class 9)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 2160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 2159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 2158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 2156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 3591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 3592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 923, 1, 'vanilla-148h-mainhand-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 19295, 1, 'vanilla-148h-offhand-flower');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 5211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (10, 9, 6948, 1, 'vanilla-148h-hearthstone');

-- warrior (class 1)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 2153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 2152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 2151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 2149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 2148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 2150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 923, 1, 'vanilla-148h-mainhand-sword');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 2442, 1, 'vanilla-148h-offhand-shield');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 1, 6948, 1, 'vanilla-148h-hearthstone');

-- paladin (class 2)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 2, 2153, 1, 'vanilla-148h-mail-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 2, 2152, 1, 'vanilla-148h-mail-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 2, 2151, 1, 'vanilla-148h-mail-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 2, 2149, 1, 'vanilla-148h-mail-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 2, 2148, 1, 'vanilla-148h-mail-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 2, 2150, 1, 'vanilla-148h-mail-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 2, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 2, 924, 1, 'vanilla-148h-mainhand-2h-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 2, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 2, 6948, 1, 'vanilla-148h-hearthstone');

-- hunter (class 3)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 923, 1, 'vanilla-148h-mainhand-melee');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 3027, 1, 'vanilla-148h-ranged-bow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 2515, 200, 'vanilla-148h-ammo-arrow');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 11362, 1, 'vanilla-148h-quiver');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 3, 6948, 1, 'vanilla-148h-hearthstone');

-- priest (class 5)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 2160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 2159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 2158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 2156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 3591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 3592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 925, 1, 'vanilla-148h-mainhand-mace');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 3422, 1, 'vanilla-148h-offhand-wildflowers');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 5211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 5, 6948, 1, 'vanilla-148h-hearthstone');

-- shaman (class 7)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 2141, 1, 'vanilla-148h-leather-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 2146, 1, 'vanilla-148h-leather-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 2145, 1, 'vanilla-148h-leather-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 2143, 1, 'vanilla-148h-leather-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 2142, 1, 'vanilla-148h-leather-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 2144, 1, 'vanilla-148h-leather-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 927, 1, 'vanilla-148h-mainhand-axe');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 2442, 1, 'vanilla-148h-offhand-shield');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 46978, 1, 'vanilla-148h-relic-totem');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 7, 6948, 1, 'vanilla-148h-hearthstone');

-- mage (class 8)
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 2160, 1, 'vanilla-148h-cloth-chest');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 2159, 1, 'vanilla-148h-cloth-legs');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 2158, 1, 'vanilla-148h-cloth-hands');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 2156, 1, 'vanilla-148h-cloth-feet');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 3591, 1, 'vanilla-148h-cloth-waist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 3592, 1, 'vanilla-148h-cloth-wrist');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 2240, 1, 'vanilla-148h-cape');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 928, 1, 'vanilla-148h-mainhand-staff');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 5211, 1, 'vanilla-148h-ranged-wand');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 4238, 3, 'vanilla-148h-bag-linen');
INSERT INTO playercreateinfo_item (race, class, itemid, amount, Note) VALUES (11, 8, 6948, 1, 'vanilla-148h-hearthstone');
-- }}}

-- {{{ playercreateinfo_skills — starter weapon skill at 100 per (race, class)

-- warrior
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (1, 1, 43, 100, 'vanilla-148h-human-warrior-swords-1h-100');

-- paladin
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (1, 2, 160, 100, 'vanilla-148h-human-paladin-maces-2h-100');

-- rogue
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (1, 8, 173, 100, 'vanilla-148h-human-rogue-daggers-100');

-- priest
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (1, 16, 54, 100, 'vanilla-148h-human-priest-maces-1h-100');

-- mage
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (1, 128, 136, 100, 'vanilla-148h-human-mage-staves-100');

-- warlock
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (1, 256, 43, 100, 'vanilla-148h-human-warlock-swords-1h-100');

-- warrior
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (2, 1, 43, 100, 'vanilla-148h-orc-warrior-swords-1h-100');

-- hunter
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (2, 4, 44, 100, 'vanilla-148h-orc-hunter-axes-1h-100');

-- rogue
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (2, 8, 54, 100, 'vanilla-148h-orc-rogue-maces-1h-100');

-- shaman
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (2, 64, 54, 100, 'vanilla-148h-orc-shaman-maces-1h-100');

-- warlock
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (2, 256, 43, 100, 'vanilla-148h-orc-warlock-swords-1h-100');

-- warrior
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (4, 1, 43, 100, 'vanilla-148h-dwarf-warrior-swords-1h-100');

-- paladin
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (4, 2, 54, 100, 'vanilla-148h-dwarf-paladin-maces-1h-100');

-- hunter
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (4, 4, 45, 100, 'vanilla-148h-dwarf-hunter-bows-100');

-- rogue
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (4, 8, 173, 100, 'vanilla-148h-dwarf-rogue-daggers-100');

-- priest
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (4, 16, 54, 100, 'vanilla-148h-dwarf-priest-maces-1h-100');

-- warrior
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (8, 1, 229, 100, 'vanilla-148h-nightelf-warrior-polearms-100');

-- hunter
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (8, 4, 45, 100, 'vanilla-148h-nightelf-hunter-bows-100');

-- rogue
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (8, 8, 43, 100, 'vanilla-148h-nightelf-rogue-swords-1h-100');

-- priest
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (8, 16, 54, 100, 'vanilla-148h-nightelf-priest-maces-1h-100');

-- druid
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (8, 1024, 136, 100, 'vanilla-148h-nightelf-druid-staves-100');

-- warrior
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (16, 1, 43, 100, 'vanilla-148h-undead-warrior-swords-1h-100');

-- rogue
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (16, 8, 43, 100, 'vanilla-148h-undead-rogue-swords-1h-100');

-- priest
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (16, 16, 54, 100, 'vanilla-148h-undead-priest-maces-1h-100');

-- mage
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (16, 128, 136, 100, 'vanilla-148h-undead-mage-staves-100');

-- warlock
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (16, 256, 43, 100, 'vanilla-148h-undead-warlock-swords-1h-100');

-- warrior
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (32, 1, 43, 100, 'vanilla-148h-tauren-warrior-swords-1h-100');

-- hunter
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (32, 4, 45, 100, 'vanilla-148h-tauren-hunter-bows-100');

-- shaman
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (32, 64, 160, 100, 'vanilla-148h-tauren-shaman-maces-2h-100');

-- druid
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (32, 1024, 136, 100, 'vanilla-148h-tauren-druid-staves-100');

-- warrior
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (64, 1, 43, 100, 'vanilla-148h-gnome-warrior-swords-1h-100');

-- rogue
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (64, 8, 173, 100, 'vanilla-148h-gnome-rogue-daggers-100');

-- mage
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (64, 128, 136, 100, 'vanilla-148h-gnome-mage-staves-100');

-- warlock
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (64, 256, 43, 100, 'vanilla-148h-gnome-warlock-swords-1h-100');

-- warrior
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (128, 1, 172, 100, 'vanilla-148h-troll-warrior-axes-2h-100');

-- hunter
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (128, 4, 45, 100, 'vanilla-148h-troll-hunter-bows-100');

-- rogue
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (128, 8, 173, 100, 'vanilla-148h-troll-rogue-daggers-100');

-- priest
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (128, 16, 54, 100, 'vanilla-148h-troll-priest-maces-1h-100');

-- shaman
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (128, 64, 172, 100, 'vanilla-148h-troll-shaman-axes-2h-100');

-- paladin
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (512, 2, 55, 100, 'vanilla-148h-bloodelf-paladin-swords-2h-100');

-- hunter
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (512, 4, 229, 100, 'vanilla-148h-bloodelf-hunter-polearms-100');

-- rogue
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (512, 8, 43, 100, 'vanilla-148h-bloodelf-rogue-swords-1h-100');

-- priest
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (512, 16, 54, 100, 'vanilla-148h-bloodelf-priest-maces-1h-100');

-- mage
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (512, 128, 136, 100, 'vanilla-148h-bloodelf-mage-staves-100');

-- warlock
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (512, 256, 43, 100, 'vanilla-148h-bloodelf-warlock-swords-1h-100');

-- warrior
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (1024, 1, 43, 100, 'vanilla-148h-draenei-warrior-swords-1h-100');

-- paladin
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (1024, 2, 160, 100, 'vanilla-148h-draenei-paladin-maces-2h-100');

-- hunter
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (1024, 4, 45, 100, 'vanilla-148h-draenei-hunter-bows-100');

-- priest
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (1024, 16, 54, 100, 'vanilla-148h-draenei-priest-maces-1h-100');

-- shaman
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (1024, 64, 44, 100, 'vanilla-148h-draenei-shaman-axes-1h-100');

-- mage
INSERT INTO playercreateinfo_skills (raceMask, classMask, skill, `rank`, comment) VALUES (1024, 128, 136, 100, 'vanilla-148h-draenei-mage-staves-100');
-- }}}

COMMIT;
